### ISSUE TITLE
core count in 03_multiple_pilots.py example

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.pilot#1029]
I am a bit confused. On localhost example runs, but core count for all resources is hardcoded as 64. On a workflow machine there are only 8 cores, but it still runs.... shouldn't core count be picked according to config?

**Comment by andre-merzky** [comment]
For localhost, we basically fake arbitrary core and node counts, specifically for the reason to be able to run examples w/o change.  See comments in line 27 and 35 in https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/rm/fork.py.  That allows us to also run arbitrary agent configurations on localhost, which otherwise would require multiple physical nodes...

**Comment by antonst** [comment]
But this means that the core count still can be picked from the config, since it would work with 1,2,4,8,...inf cores. It does not take much to check availability of cores and spot this inconsistency, but if it is < 8 this is not the case. Also as a user, I would like to know on how many cores the pilot is actually running. Just my 5 cents....

**Comment by andre-merzky** [comment]
Hmm, maybe I am misunderstanding the question.  Would you mind rephrasing where the expectation/reality mismatch is?  Sorry...

**Comment by antonst** [comment]
This actually applies to all examples and not only to multiple pilots example. Core count regardless of the resource is hard-coded as 64. On a workflow machine we only have 8 cores. This can raise some questions. If you set core count in config for localhost as 2 or 1 this should be OK.

**Comment by andre-merzky** [comment]
Got it, thanks!

**Comment by andre-merzky** [comment]
This has been addressed in the examples.
