### ISSUE TITLE
Units Hang on Stampede despite having actually executed

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1068]
Hello. I've been trying to run pilot jobs of 1024 CUs, but the pilot fails to exit cleanly to the `Done` state. I'm not sure whether this problem falls under RP or RU, as I suspect the problem has to do with logging of the timings of the unit state transition.

Upon analysis of the associated session directory in the `radical.pilot.sandbox`, I find that all the units do in fact complete correctly. I have confirmed this by checking that every unit produces the proper `STDOUT`. More interestingly, the units which are not recorded as having completed have `Nan` values for the states `Executing`, `StagingOutput`, and `Done`, but not for `AgentStagingOutputPending`, `AgentStagingOutput`, `PendingOutputStaging`. According to the state model, a unit which enters `PendingOutputStaging` has also made it successfully to `Executing`, but the recorded states go against the state model.

I have been able to run jobs with 16 ,32 , ... , 512 CUs with no problem. This only occurs for 1024 CUs. And even then, at most 45 CUs fail to complete correctly.

I am using RP version `0.40.3`, RU version `v0.41.1-9-gff0f8b1@devel`, `v0.41-40-g0754105@feature-osg_optimizations`.

**Comment by marksantcroos** [comment]
This is a 'known' RP issue, not related to Stampede, nor related to logging.
I've been able to workaround/ignore it so far, but this definitely needs addressing.

**Comment by marksantcroos** [comment]
You might want to give the fix/state_update_sorting branch a swing.

**Comment by mingtaiha** [comment]
I'm testing it right now. I'll keep you posted.

**Comment by mingtaiha** [comment]
I managed to run /bin/sleep on Stampede for 1024 cores successfully. I am going to try for 2048 CUs, possibly 4096 CUs just to test.

**Comment by mingtaiha** [comment]
I ran `/bin/sleep 30` for 2048 and 4096 CUs on Stampede and the states came out alright. What was the issue in the code? What did you do to fix it?

**Comment by marksantcroos** [comment]
Great, and thanks for performing the tests!

Andre fixed the update logic in this commit: https://github.com/radical-cybertools/radical.pilot/commit/1d02c77262958f8fd1e66efe0448af6031cae7fb

**Comment by andre-merzky** [comment]
Indeed, thanks for the testing!

The problem was a logic error in the code section Mark pointed you to.  That code pushes state updates to MongoDB -- but in that version of RP, the state updates can come in arbitrary order.

Although they are *mostly* ordered, messages on some communication channel can be faster than on others, and overtake 'earlier' notifications.  If that happens, we delay the sending of notifications until a consistent sequence of state transitions can be pushed (according to our unit state model).   The logic error was in that part: the code kept track of the state of the individual units -- but it remembered any state it saw as last state, not the *actual* last state wrt. the state model.  So, on some overtaking state messages, it pushed earlier states after later states, which overwrote the unit state in the DB.  If that happened  the client would never pick up the units, as they never saw the respective state reached.  This was rather rare though, but any pair of consecutive unit state transitions had that chance, so the chances added up for large runs...

I'll start the process of merging the fix then.  We'll wait until end of week to see if we can get a solution on the environment problem, but will then start the release procedure.
