### ISSUE TITLE
Blue waters: Units stuck in 'AgentStagingInputPending' state

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.pilot#1086]
I am using RP 0.41 and consistently see this happening. Any ideas?

**Comment by antonst** [comment]
Exactly the same workload runs on Stampede just fine.

**Comment by andre-merzky** [comment]
see #1071 and  #1068.  Antons, as commented on #1071, can you please give the `fix/state_update_sorting` branch a try?  That is supposed to solve that problem.

**Comment by andre-merzky** [comment]
PS.: in case that turns out to be a different problem, you would need to provide more information: what is the CU description, what is in the logfiles, etc.  You know the drill, right? :)

**Comment by antonst** [comment]
It is different. I think this is triggered by the size of the simulation input files.

**Comment by antonst** [comment]
With ```fix/state_update_sorting``` pilot fails on BW, no CUs were executed. 
[sandbox](https://github.com/antonst/rp-logs/blob/master/sandbox.tar.gz)
[log](https://github.com/antonst/rp-logs/blob/master/bw-sync-r8-c288-s1000-1.log)

**Comment by marksantcroos** [comment]
This will fail on BW because of the anaconda fix/env breakage on that branch (essentially devel)

**Comment by antonst** [comment]
OK, thanks Mark.

**Comment by andre-merzky** [comment]
Antons, is there any action needed on this one?

**Comment by andre-merzky** [comment]
We consider anaconda not fully supported.  BW otherwise passes testing right now.

**Comment by mturilli** [comment]
I am afraid anaconda support needs explicit consideration: All the current and potential users I met so far use anaconda, no exception found.

**Comment by andre-merzky** [comment]
Hey Matteo - I hear what you are saying, and that needs to be taken into account.  This specific ticket though is for anaconda on the *target* resource, and also specific to Blue Waters.  Is this  ticket actionable as such in your opinion, or would it be better to open a new ticket if there is a more general pain point on anaconda support?

As a general remark: I am not sure we need to support all possible python installations for a given resource as agent runtime environment.  The CUs need to be able to use any python deployment - but that is a different issue altogether, right?

**Comment by mturilli** [comment]
Hey Andre, thank you for the clarification. 

I think we should consider the following requirements:
1. The user wants to use anaconda to execute an application that imports RP;
2. The user wants to use RP to execute an application that requires anaconda.

I think we should not consider the following requirement:
3. A developer wants to use anaconda to code RP.

If this ticket is about requirement 2 and the issue is that BW does not support anaconda as required by the application of the user, then we should not consider this a RP problem. On the other hand, if the problem is that we are not able to use the anaconda installation of BW, then we should evaluate this issue further and therefore not close the ticket or open a new, more focused ticket.

Would you agree with the general approach? Specifically, I am not sure how well all this applies to this ticket :) There is not enough information in it for an evaluation.


 , this should not be considered a valid **user** requirement
