### ISSUE TITLE
Probes inside CU's task

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1137]
Can we add some probes to get information from inside a CU task in the database?

**Comment by andre-merzky** [comment]
Yep, as said, this can be done.

**Comment by andre-merzky** [comment]
Hi Iannis, 

please have a look at the `feature/cu_prof` branch (which needs the `feature/profile` of radical.utils.  In that branch, you will always find a `PROF` file in the unit sandbox.  You can add your own profile probes to that file, as long as you adhere to the profile format we use, which would be something like:

```
1476481441.6759,unit_script:MainThread,unit.000068,Executing,after_exec,test probe
```

The comma-separated fields are:

  * *time*: in seconds since epoch, float
  * *owner*: who wrote the timestamp
  * *uid*: the unit uid (is set as `RP_UNIT_ID` in the environment) 
  * *state*: the unit state (`Executing` for your case)
  * *event*: a unique name identifing the probe 
  * *msg*: a human readable message (can be empty)

You should in general use `unit` as value for the *owner* field I think.

After the unit completed, the probes will be picked up and inserted into the global session profile.

**Comment by andre-merzky** [comment]
ping @iparask  - does that work as expected?

**Comment by iparask** [comment]
Hello Andre,

I haven't forgot about it. I will check it during the weekend and give you feedback

**Comment by andre-merzky** [comment]
Hey, any updates on this one? :)

**Comment by iparask** [comment]
Yes! It works! Thank you and very sorry for doing it so late

**Comment by andre-merzky** [comment]
thanks,  and no worries!  The branch will need some cleanup though before being merged and released, I am not sure if we get this into the next release :/

**Comment by andre-merzky** [comment]
This has been merged by now.
