### ISSUE TITLE
Cannot cancel CU when in `AgentStagingOutputPending` state

### ISSUE THREAD

**Issue by jhprinz** [radical-cybertools/radical.pilot#1181]
I tried to cancel a non-finished CU but apparently it was in a state that is not capured by the
`unit.cancel` method. 

```
  File ".../myenv/lib/python2.7/site-packages/radical/pilot/compute_unit.py", line 525, in cancel
    raise IncorrectState("Unknown Compute Unit state: %s, cannot cancel" % self.state)
radical.pilot.exceptions.IncorrectState: Unknown Compute Unit state: AgentStagingOutputPending, cannot cancel
```

I assume the function just needs updating. For now I will just wait for those CUs to finish. They are almost complete anyway and it makes more sense to keep them running.

**Comment by andre-merzky** [comment]
Thanks for the report, Jan!  This is fixed in a different branch (hi Mark!), but that branch will need quite some time until it gets merged into devel.  I'll check if I can backport (or re-implement) the fix in the current devel.

How much of a problem is that (apart from the fact that its clearly an error on our part)?

**Comment by jhprinz** [comment]
For me no problem right now. I just wanted to note this as a potential unintented behaviour. It looked like you extended the stages and this was not yet uptodate. Don't worry because of me. I have a simple workaround

**Comment by andre-merzky** [comment]
thanks.

**Comment by andre-merzky** [comment]
This has been merged in the last release.
