### ISSUE TITLE
Modules are not being accessed on Comet

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1190]
I am doing a ```module load python scipy``` and then

```
python -c 'import scipy'
```
and I get the following error
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named scipy
```

Clearly, the CU env is not the one offered by Comet.

**Comment by iparask** [comment]
If I do ``` which python``` from a CU I get

```
/home/iparask/radical.pilot.sandbox/ve_comet/bin/python
````
This shouldn't be the case

**Comment by andre-merzky** [comment]
How are you doing the 'module load'?  In the CU pre-exec?  What version of RP are you using, and what resource label?

Thanks, Andre.

**Comment by iparask** [comment]
I am doing module load in the pre-exec of a CU and I am using ```xsede.comet```

**Comment by andre-merzky** [comment]
Iannis, any luck with the devel branches?  You may also want to have a look at #1267.

**Comment by iparask** [comment]
Zero luck Andre.... I run an example where I loaded the python module on Comet and tried then to import numpy, which exists in the module.

Here are RADICAL-stack, radical_pilot_cu_launch_script.sh, STDOUT and STDERR:

```
python            : 2.7.6
virtualenv        : /home/iparask/Virtualenv/RadicalDevel
radical.utils     : v0.45-2-g82050c5@devel
saga-python       : split-9-gf9b04d8@devel
radical.pilot     : split-27-g8e6be2b@devel
radical.analytics : v0.1-115-g31b5065@master
```

```
[iparask@comet-ln3 unit.000000]$ cat  radical_pilot_cu_launch_script.sh
#!/bin/sh


# Change to working directory for unit
cd /home/iparask/radical.pilot.sandbox/rp.session.js-172-81.jetstream-cloud.org.iparask.017238.0003/pilot.0000/unit.000000
# Environment variables
export RP_SESSION_ID=rp.session.js-172-81.jetstream-cloud.org.iparask.017238.0003
export RP_PILOT_ID=pilot.0000
export RP_AGENT_ID=agent_1
export RP_SPAWNER_ID=agent.executing.0.child
export RP_UNIT_ID=unit.000000

# Pre-exec commands
module load python
# The command to run
/home/amerzky/ompi//installed/2017_02_17_6da4dbb/bin/orterun  --hnp "142278656.0;tcp://10.22.252.106,198.202.117.185,10.21.252.106,192.168.32.244:39079;ud://420726.28688.1"  -np 1 -host comet-14-53 python "-c" "import numpy;print numpy.__version__"
RETVAL=$?
# Exit the script with the return code from the command
exit $RETVAL
```

```
[iparask@comet-ln3 unit.000000]$ cat STDOUT
[ORTE] Task: 0 is launched! (Job ID: [2171,1])
```

```
[iparask@comet-ln3 unit.000000]$ cat STDERR
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
```

From what I understand the pre-exec conditions are executed at the master node and not where the user script is going to be executed. I would propose that ORTE executes the shell script of the CU and not just the executable.

**Comment by andre-merzky** [comment]
> From what I understand the pre-exec conditions are executed at the master node and not where the user script is going to be executed.

Yes indeed.

> I would propose that ORTE executes the shell script of the CU and not just the executable.

That won't work for MPI CUs.  Do you use MPI?  If not, then a workaround is to specify /bin/sh as executable, and run a script which first does the module load, then executes your application.  Not a nice approach, but the quickest way to get things working for you.

**Comment by iparask** [comment]
Hello Andre,

as I have said, I installed all the dependencies in the VE in the resource. That is my workaround.

I am not using MPI, but assume the scenario: An MPI CU with n cores is dependent to ```pnetcdf```, which is offered by the system as a module. Including it to the pre_exec, will not load the module and the CU will fail.

In such a case, is a shell script with the module dependencies good enough for execution or it will fail before start?

**Comment by andre-merzky** [comment]
Note on how this could be implemented properly (Iannis, feel free to ignore):

Currently, the agent's LM creates a hop command (hop to the target node), and a launch command (launch the app executable).  If the hop command is non-empty, that is what is being executed, with the expectation that the launch command is triggered on the target node.

In either case, the pre- and post- exec commands are explicitly part of the startup script, and run independently from the hop- and launch- commands.

In the case of ORTE, we could move the pre- and post- exec to the launch command (thus resulting in a shell script instead of the application executable), and define orterun to be a hop command.  For MPI, that creates the obvious problem that multiple instances of that launch command are executed, and thus the pre- and post- exec are running multiple times.  To avoid that they would have to be guarded by something like `if test "$OMPI_COMM_WORLD_RANK" == "0"`.

At this point it probably makes sense to separate out hop_command, launch_command, and application_command, and also to make this more consistent over the different launch methods and executors -- I don't think they are consistently handled at the moment.

I'm afraid that this goes beyond the scope currently planned for this problem space / ticket.  Meanwhile, we should document the workaround of crafting the respective scripts manually.


Mark also mentioned another option which seems promising, but has a similar implementation effort AFAICS: the agent could enact the pre- and commands on the agent node, store the result in an 'env set', and apply those environment setting to all units which specify the same pre-exec command.  This would be very performant, but also has some drawbacks:

  -  actions are not CU specific
  - this only applies to (explicit or implicit) env settings,
  - it does not really very useful for post exec.

But specifically for virtualenv activate and similar activities this seems to be a useful approach.

**Comment by andre-merzky** [comment]
> as I have said, I installed all the dependencies in the VE in the resource. That is my workaround.

Right

> I am not using MPI, but assume the scenario: An MPI CU with n cores is dependent to pnetcdf, which is offered by the system as a module. Including it to the pre_exec, will not load the module and the CU will fail.
> 
> In such a case, is a shell script with the module dependencies good enough for execution or it will fail before start?

I am not sure if it will fail actually - but this approach will certainly not work for all kinds of pre-execs.

**Comment by marksantcroos** [comment]
The following comment from Andre is in my mailbox but not in this ticket, so seems to be removed:

Note on how this could be implemented properly (Iannis, feel free to ignore):

Currently, the agent's LM creates a hop command (hop to the target node), and a launch command (launch the app executable). If the hop command is non-empty, that is what is being executed, with the expectation that the launch command is triggered on the target node.

In either case, the pre- and post- exec commands are explicitly part of the startup script, and run independently from the hop- and launch- commands.

In the case of ORTE, we could move the pre- and post- exec to the launch command (thus resulting in a shell script instead of the application executable), and define orterun to be a hop command. For MPI, that creates the obvious problem that multiple instances of that launch command are executed, and thus the pre- and post- exec are running multiple times. To avoid that they would have to be guarded by something like if test "$OMPI_COMM_WORLD_RANK" == "0".

At this point it probably makes sense to separate out hop_command, launch_command, and application_command, and also to make this more consistent over the different launch methods and executors -- I don't think they are consistently handled at the moment.

I'm afraid that this goes beyond the scope currently planned for this problem space / ticket. Meanwhile, we should document the workaround of crafting the respective scripts manually.

Mark also mentioned another option which seems promising, but has a similar implementation effort AFAICS: the agent could enact the pre- and commands on the agent node, store the result in an 'env set', and apply those environment setting to all units which specify the same pre-exec command. This would be very performant, but also has some drawbacks:

- actions are not CU specific
- this only applies to (explicit or implicit) env settings,
- it does not really very useful for post exec.

But specifically for virtualenv activate and similar activities this seems to be a useful approach.

**Comment by andre-merzky** [comment]
Yeah, I removed it, I think that might kind of work, but adds other complications.  Like, the env settings would need to be done for all ranks, not only rank 0.  Also, a barrier might be needed to do something like data pre-processing so that other ranks don't start before that's done.  One could possibly solve those things by splitting into env-related pre-execs (needed for all ranks) and non-env-pre-execs (rank 0, needs barrier), but that is fickly I think.

I guess we ultimately need to distinguish those two types of pre-execs, they are too different semantically.  We discourage the data-processing pre-exec anyway (should be a separate CU, but that complicates data handling to some extent, and needs CU dependencies to be really useful).  For the env-related pre-execs, we may need to bite the bullet and export large sets of the env to the process, via `-x` args to orterun.  I am not exactly sure how that would translate to orte_lib - this would probably only really work well with Mark's approach to environment sets...

Anyway,  this whole topic is a can of worms, really - which is not surprising, giving the number of tickets related to the topic in one way or the other...

**Comment by mturilli** [comment]
Note: this also affects experiments for the AIMES-Experience paper on Comet.

**Comment by ibethune** [comment]
This is complex and we don't have a plan to address this right now (or have any hope of fitting it in before the release).
