### ISSUE TITLE
oliver's ticket

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.pilot#1198]
Giannis,

My pilot job fails with a

…
2017-02-03 18:24:02,208: radical.pilot       : MainProcess                     : MainThread     : DEBUG   : session SPIDAL_tutorial closed   umgr   umgr.0000
2017-02-03 18:24:02,209: radical.pilot       : MainProcess                     : MainThread     : DEBUG   : session SPIDAL_tutorial closed
session lifetime: 79.6s                                                       ok
Traceback (most recent call last):
 File "rp_psa.py", line 186, in <module>
   units = umgr.submit_units (cudesc_list)
 File "/home1/02102/orbeckst/miniconda2/envs/mdaenv/lib/python2.7/site-packages/radical/pilot/unit_manager.py", line 414, in submit_units
   raise ValueError('cannot submit no unit descriptions')
ValueError: cannot submit no unit descriptions

and no output is produced. Can you (or someone else) please help and have a look? More details at 

	https://github.com/Becksteinlab/SPIDAL-MDAnalysis-Midas-tutorial/issues/1

Thanks!

Oliver

p.s.: sorry for the spam ,please feel free to tell me that you don't want a cc…

See More from Oliver Beckstein

--
Oliver Beckstein, DPhil * oliver.beckstein@asu.edu
http://becksteinlab.physics.asu.edu/

Assistant Professor of Physics
Arizona State University
Center for Biological Physics and Department of Physics
Tempe, AZ 85287-1504
USA

**Comment by orbeckst** [comment]
See Becksteinlab/SPIDAL-MDAnalysis-Midas-tutorial#1 .

**Comment by iparask** [comment]
From Oliver:
> I am logged into TACC stampede (login2).
> The DB is MongoDB on our server; I can telnet to the port. If you need access, email me.
> It's on stampede so I didn't think about getting a certificate with myproxy; however, I can use gsissh to log into any of the other login nodes without password.

**Comment by andre-merzky** [comment]
Could it be that the cudesc_list is empty?

Cheers, Andre



On Feb 4, 2017 01:57, "Shantenu" <notifications@github.com> wrote:

Giannis,

My pilot job fails with a

…
2017-02-03 18:24:02,208: radical.pilot : MainProcess : MainThread : DEBUG :
session SPIDAL_tutorial closed umgr umgr.0000
2017-02-03 18:24:02,209: radical.pilot : MainProcess : MainThread : DEBUG :
session SPIDAL_tutorial closed
session lifetime: 79.6s ok
Traceback (most recent call last):
File "rp_psa.py", line 186, in
units = umgr.submit_units (cudesc_list)
File "/home1/02102/orbeckst/miniconda2/envs/mdaenv/lib/
python2.7/site-packages/radical/pilot/unit_manager.py", line 414, in
submit_units
raise ValueError('cannot submit no unit descriptions')
ValueError: cannot submit no unit descriptions

and no output is produced. Can you (or someone else) please help and have a
look? More details at

https://github.com/Becksteinlab/SPIDAL-MDAnalysis-Midas-tutorial/issues/1

Thanks!

Oliver

p.s.: sorry for the spam ,please feel free to tell me that you don't want a
cc…

See More from Oliver Beckstein

--
Oliver Beckstein, DPhil * oliver.beckstein@asu.edu
http://becksteinlab.physics.asu.edu/

Assistant Professor of Physics
Arizona State University
Center for Biological Physics and Department of Physics
Tempe, AZ 85287-1504
USA

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/radical-cybertools/radical.pilot/issues/1198>, or mute
the thread

**Comment by orbeckst** [comment]
@andre-merzky – Yes, that was the case: I managed to mess up a range (!), see @iparask fix in PR Becksteinlab/SPIDAL-MDAnalysis-Midas-tutorial#2

This is fixed and can be closed. Thank you!
