### ISSUE TITLE
VE upgrade failed due to dependency version check

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/radical.pilot#1217]
This is split from #1216 to investigate the pilot's failure to fail...

client log and bootstrap output are at https://gist.github.com/ibethune/36124be2127e52cb69d51ca559b927b6

**Comment by andre-merzky** [comment]
*sigh*  Nothing is ever easy...  Here is what happens:

The virtualenv for the pilot is usually split into two parts: a resource specific proper virtualenv which contains all pre-requisites, and `rp_install`, which is pilot specific and contains the radical stack and all additional pilot specific dependencies.  We stage tarballs for the radical stack deployment, which you'll see appearing in the pilot sandbox before the job starts -- in this case those are tarballs for `v0.45.RC1`.

Now, we recently introduced *versioned* dependencies in our stack, to simplify VE upgrades, which means that, for example, RS `v0.44` has the dependency `radical.utils>=0.44`.  That is also the case for the release candidate -- we only update those dependencies before pushing out a release to pypi, because otherwise some RC installations fail because they can't find dependencies in pypi.

What happens in your case is that RU `v0.45.RC1` gets installed all right, but on RS install of `v0.45.RC1`, pip finds `radical.utils>=0.44` **but considers RU v0.45.RC1 insufficient** to meet that requirement.  Bah!

I don't think that this is a problem with how we number the RCs, at least not primarily: I have seen similar problems with non-RC packages at some point, and got rid of it by reverting to an older pip or setuptools version (can't remember).

'*lange Rede, kurzer Sinn*', as we Germans say (*long speech, little content*): I would propose to remove versioned dependencies, which may result in some pain on upgrading VEs, but I think we do enough chasing of python installation issues to not add another can of worms.  Happy to discuss, maybe there are other solutions to this...

**Comment by andre-merzky** [comment]
Comment copied over from #1216:

> The shared VE seems to be fine after all, I don't think there is action needed on that end, thanks!
>
> For the record: we have a small tool in RP (bin/radicalpilot-create-static-ve), which, as the name suggests, supports the creation of a shared static VE on that kind of resources. Testing that tool is not part of the test protocol though, as its rarely needed, and its usually a member of the group who creates and maintains those VEs.

**Comment by ibethune** [comment]
IMO versioning makes sense for the client-side installation, and should work correctly for released packages i.e. if a user pip installs a version of RP from pypi they should get up-to-date SAGA and RU.

I'm not sure it makes sense for setting up the rp_install on the execution host, where we explicitly stage a specific set of tarballs from the client  (do we always do this, or are there cases where we expect code to be pulled down from pypi?) .  Could the fix be as simple as adding --no-deps to the $pip_flags in rp_install() and then we manually install each of the $RP_INSTALL_SOURCES, or does this screw up if the other (external) dependencies are missing?

At least in my testing by hand, this allowed me to manually install RU, RP and SAGA packages in the rp_install directory without futher errors.

**Comment by andre-merzky** [comment]
We indeed don't always stage the tarballs, we also have the option to pull from pypi.  But also, we kind of have to use the same `setup.py` for both modes -- or at least it would add more (or different) complexity to maintain different `setup.py` variants, depending on the installation target.

`--no-deps` would probably a solution indeed.  We so far did not use it to have some fail safety on incomplete resource-specific virtualenvs, as any missing dependency would then be pulled in most cases -- but (a) that pull does not always work anyway (firewall), and (b) that only masks other problems in the ve setup.  So yeah, we may want to consider returning to this mode.

Let me know if you think this should be addressed for this release, and I'll give it a spin!

**Comment by ibethune** [comment]
I'm thinking not for this release.  These changes are too risky and would need properly tested across a wide range of resources (i.e. essentially restarting the pre-release test process).  The only benefit would be for ARCHER, where we have 0 users anyway.  I note that the dependency check appears to be working OK for released code (I tried with the 0.44 release).  I suggest we leave ARCHER in the state of "probably working, not tested" for this release and decide if we want to include it in the next one, in which case we need to address this issue so we can test with pre-release code versions.

**Comment by mturilli** [comment]
Is archer still supported? If not, I would close.

**Comment by andre-merzky** [comment]
Ack.  Closed in favor of #1260 which is the generic ticket for this issue.
