### ISSUE TITLE
Set up a new shared VE on ARCHER

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/radical.pilot#1222]
The current shared ve is in /work/e290/shared which will be destroyed on 9th April.  A better long-term alternative is in /work/y07 (software packages).  This can be set up after the 0.45 release.

**Comment by ibethune** [comment]
@andre-merzky is there some documentation on how to set up a suitable shared VE?

**Comment by andre-merzky** [comment]
Even better: there is a tool for that: https://github.com/radical-cybertools/radical.pilot/blob/devel/bin/radicalpilot-create-static-ve :)

Well, maybe not better, since w/o docs that is probably not useful.  But I am not sure we want to expose the creation of static VEs to end users really at this point.

**Comment by ibethune** [comment]
OK, let me try that...

**Comment by ibethune** [comment]
A new shared VE is installed on ARCHER containing the RP dependencies only (not RP itself).  I tested with the 00_getting_started.py script and it works.

**Comment by ibethune** [comment]
For reference, it is located in ```/work/y07/y07/cse/radical.pilot/shared_pilot_ve_20170324/```
