### ISSUE TITLE
RP 0.45 depends on utils and saga >= 0.44

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/radical.pilot#1260]
If I install the latest release from pip, the dependencies seem to specify that 0.44 would be suitable.  For a clean install this is no issue, it grabs the latest versions of the whole stack, but it is possible to end up with a stack that looks like:

```
pip list
...
radical.pilot (0.45)
radical.utils (0.44)
saga-python (0.44)
```

Should we really be requiring version 0.45 in the deps?  I have no idea if the above stack even has any hope of working...

**Comment by marksantcroos** [comment]
How would you end up with such a stack?
Generally the only way would be if you would have intentionally done `pip install --upgrade --no-deps radical.pilot`? (And if you wouldn't specify `--upgrade` it wouldn't update RP either)

**Comment by ibethune** [comment]
Yes, it is rather difficult to end up in this situation.  If we do a hotfix for #1254 then we should also fix this at the same time.  If not we should use this ticket to be sure the dependencies are correct for 0.46 (where we will certainly require saga-python and radical.utils 0.46).

**Comment by andre-merzky** [comment]
Hey folx, 

we started to look into versioned dependencies only recently -- but I am actually inclined to remove them altogether, even though that implies that we could end up with an invalid stack.  The reason is that some pip versions always enforce an upgrade if a versioned dependency is defined, even if the right version is available.  That screws agent sandbox installation on machines with a firewall, such as supermuc, where the only workaround I could find was exactly removing the version requirements.

An alternative would be to implement some version checks during module loading, like:

```python
# .../radical/pilot/__init__.py
import radical.utils as ru
import distutils.version as dv

assert (dv.LooseVersion(ru.version) == dv.LooseVersion("0.46"))
```

That is ugly for sure, and doesn't help during install - but it might be better than no check at all.

**Comment by mturilli** [comment]
@andre-merzky Did we converged on this?

**Comment by andre-merzky** [comment]
No progress on this one - defining versioned deps is the right thing to do, but I do not know how to work around the pip problem.  For now we make sure that the releases of the stack which have the same minor version work together, and that the latest releases for all layers form a valid stack.
