### ISSUE TITLE
Empty pilot.0000.prof.tgz in session folder of radical.pilot.sandbox on XSEDE resources

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1286]
Hello. I've been running pilot on Stampede, SuperMIC, Comet, and Gordon, where the CUs are emulations of a Synapse profile. I have been looking in the different session directories in `radical.pilot.sandbox`, and I find that the `pilot.0000.prof.tgz` is 0 Bytes. Shouldn't there be profiles generated by the agent side in the session folder in the sandbox?

My `radical-stack`
```
python            : 2.7.6
virtualenv        : /home/mingtha/ve/ve.exec_model_exp_devel
radical.utils     : v0.45-2-g82050c5@devel
saga-python       : split-4-gaa285ca4@devel
radical.pilot     : split-29-g16298d1f@fix-issue_1276
radical.analytics : v0.1-187-g56ecce7@experiment-aimes_nodata
```

**Comment by andre-merzky** [comment]
Empty tarballs are created in the pilot sandbox even before the pilot is started.  This is done to avoid stalling on output staging for failing pilots on OSG, which happens when staging  files do not exits.

Having said that, after a successful pilot execution, and with `RADICAL_PILOT_PROFILE` set, the tarball should not be empty anymore.   Is that the case?

**Comment by mingtaiha** [comment]
I see. I'm testing it right now. Keep you posted!

**Comment by mingtaiha** [comment]
I tested it on Gordon and I get agent profs. I'll close this, and open it if it doesn't work on other machines even after setting `RADICAL_PILOT_PROFILE=TRUE`
