### ISSUE TITLE
Documenting OpenMPI dependences and compilation 

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1341]
In our collaborations with ATLAS, Princeton and Penn State we need to recompile some applications to make them work with RP and OpenMPI. Currently, we were not able to find any viable documentation to know:

- What branch/tag of OpenMPI we should use 
- What set of parameters are mandatory when compiling (for) OpenMPI  

This lack of documentation is blocking both projects. We would need this documentation to make available and, most importantly, to be kept up to date on regular basis. I do not see a 'critical' label but this has become indeed critical.

**Comment by vivek-bala** [comment]
From the work with the Princeton folks, we have 75% of the workflow tested on stampede and are ready to test on Titan. We would need compilation instructions to build the tools against openmpi. It is also necessary to have fortran support in the same ( I mention since at some point andre and I were not sure if it exists in openmpi/2017_03_24_6da4dbb-unsorted on Titan, I think that was the build that I was looking into).

**Comment by AA919** [comment]
We recently started a collaboration with University of Oregon to allow the profiling of workloads on RP with TAU. This project has the same requirements mentioned by Matteo and Vivek due to the fact that TAU needs to be compiled with the same OpenMPI that is used to run CUs.

**Comment by ibethune** [comment]
@mturilli @andre-merzky anything received from ORNL yet?  I don't remember who was in the loop with them.

IMO this issue (while undoubtedly important for ongoing work, should not be considered blocking for the release (and certainly not the RC for testing, since it will only affect documentation in the end).  Do you agree we can defer?

**Comment by mturilli** [comment]
I would agree.
