### ISSUE TITLE
Question about how to create CUs when num of cores is not equal to num of mpi procs

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1365]
I need to run tasks that each use 24 nodes on Titan. The task itself is a MPI task which will spawn 24 processes (1 proc/node) where each process uses the GPU on that node. I am trying to understand how the CU needs to be described.

I considered the following:
```
cud = rp.ComputeUnitDescription()
cud.executable = './bin/xspecfem3D'
cud.mpi = True 
cud.cores= 384                  # 24 nodes * 16 cores/node so that each CU is assigned 24 nodes
```
But this will launch the executable as follows:
```
/sw/xk6/xalt/0.7.5/bin/aprun -n 384 ./bin/xspecfem3D
```

Whereas what I need is the following:
```
aprun -n 24 -N1 ./bin/xspecfem3D
```

Thanks

**Comment by andre-merzky** [comment]
We don't have that ability at the moment.  The correct CU description would be:

```
cud.cores = 0
cud.gpus = 24
cud.mpi = True
```

while that can be specified already, it is not evaluated correctly by the agent scheduler, and it will be unable to place the units accordingly.  It is really *just* the scheduler which is missing out here (well, and some resource inspection or configuration to inform the scheduler about GPU/core layout on the resource) - but its unclear when we'll (I'll) find the time to switch attention back to that topic. :/

**Comment by vivek-bala** [comment]
I understand. But I remember that it was mentioned that, for now, the onus is on the user to describe a CU (for example 1 CU per node) such that the GPU can be used. Consider a similar case (as above), where aech CU needs to spawn 24 MPI procs over 24 nodes (1 proc per node). Can such a CU be created currently?

This is a critical requirement for the princeton usecase. It will be useful to prioritize this issue.

**Comment by andre-merzky** [comment]
No - the workaround of creating one CU per node works because that is then a non-MPI CU, and we are able to spawn then one process per node which has all cores of that node allocated.  In your case above, you *need* to spawn via MPI, but *not* for all cores we want to reserve - and the agent is not yet able to do that w/o proper information from the scheduler.

**Comment by mturilli** [comment]
Following up with Vivek on this ticket, the GPU seems to be irrelevant. The problem seems being able to specify the total number of MPI processes/tasks, i.e., `aprun -n`; and the number of processes/tasks per node, i.e., `aprun -N` (as defined on Titan, Stampede and Comet. Is there a machine we support with a different syntax/semantics for aprun?). 

Currently, RP seems to be assuming (implicitly?) `-n = -N` so that 1 MPI process/task is assumed to require 1 node. This seems a corner case of the general case in which when specifying a CU we want to define how many cores each MPI process/task should have.

If you agree with this, I would propose to disregard at the moment `cud.gpus = 24` and focus on something like 'cud.mpi_procs, cud.mpi_procs_per_node' or probably a much better alternative with the same sematics.

**Comment by andre-merzky** [comment]
Hey Matteo, Vivek, 

indeed, that perspective simplifies things somewhat.  We still need to change the scheduler to interpret those information, and to pass the resulting mapping to the execution layer though.

**Comment by andre-merzky** [comment]
Discussion continued on https://github.com/radical-cybertools/radical.pilot/wiki/GPU-and-mixed-MPI-OpenMP-units

**Comment by iparask** [comment]
Hello,

I am not able to understand why there is an ```'open_mp'``` flag in the CU description. For reference:
```
 {
    'cpu_processes'           : 6,
    'threads_per_cpu_process' : 3,
    'gpu_processes'           : 2,
    'mpi'                     : True,
    'open_mp'                 : True
  }
```

From my understanding, it does not offer any information about the launch method that the CU needs to be launched. In addition, there is a CU description attribute that allows the definition of the environment of the CU, thus any variable that is needed for correct thread spawning should be included there by the user. Just to clarify, I do not have any disagreement with defining the number of threads per process, since it will allow better process placing.

Giannis

**Comment by andre-merzky** [comment]
Assume the above CU description, and the following cluster (2 nodes with 16 cores, 2GPUs:

```
|----------------==|----------------==|

  | : node boundary
  - : cpu core (free)
  + : cpu core (process spawned)
  > : cpu core (thread spawned)
  = : gpu (free)
  # : gpu used
```

with

RP would place the CU like this:

```
|+>>>+>>>+>>>+>>>##|+>>>+>>>--------==|
```

If 'open_mp' is set, RP would set the env Variable `OMP_NUM_THREADS=3` so that your processes know they can use 3 additional cores each.  If we don't do that, one of two things will happen:

 * (i) you need to hardcode '3' in your application
 * (ii) you don't specify OpenMP thread number at all, and let OpenMP auto-pick a number.

(i) works - but you need to recompile your application (or make it dynamically configurable) when running on a different resource, or changing the core number you want to use.

(ii) is BAD: OpenMP will pick 16 threads for each (!) process we spawn - which will overload the nodes, and also interfere with any other CUs we want to put on the free cores of the second node. 

So, the 'open_mp' flag tells RP how to let the application know about the free cores.

**Comment by andre-merzky** [comment]
I would like to add some notes from a call with Giannis - @iparask, please correct / add as needed.

Giannis considers the setting of `OMP_NUM_THREADS` to be out of scope for RP, for two reasons:

  * this is an env setting which is interpreted by the application, and thus should be part of the CU description
  * we can't offer similar env settings for other threading 'methods' (plain pthreads, python thread pools, etc).

I agree with the latter: we can't.  We can though set something like `RP_NUM_THREADS`, similar to what we set in the CU env already (unit ID, sandbox location, etc).  Also, this is not about supporting all possible use cases, but only to support the OpenMP one, which arguably is relevant to us.

We continued to disagree about the first point :)

**Comment by mturilli** [comment]
Some notes from a follow up discussion we had in the lab - @iparask, please correct / add as needed.

Strictly speaking, we agreed that `'open_mp' : True` breaks the CU abstraction. A CU is a wrapper around an executable that is regarded as a **black box**. Arguably, `OMP_NUM_THREADS` is part of this black box and, as such, should not be exposed in the CU description but set by the user as an environment variable.

Keywords here are *strictly* and *arguably*. There is space for interpretation, as the boundary between a wrapper and the black box can be fuzzy: Part of the wrapper functionality is to set up the execution environment for the black box, obvious case being `'mpi': True`. `OMP_NUM_THREADS` is part of this environment, but specific to the application and not to the resource. RP should abstract only the resource properties, not the application ones.

More pragmatically, we all agreed that having this option set explicitly may help users by lowering the  barrier to adoption and/or initial failure rate. There is a point to be made about how the user should know what variable to set when using OpenMP but we also know that our goal is helping users.

**Comment by andre-merzky** [comment]
Yeah, I think we are on the same page, really... - thanks.

**Comment by andre-merzky** [comment]
This is considered solved in the gpu branches, according to [option 3 in RFC.1](https://github.com/radical-cybertools/radical.pilot/wiki/RFC.1#alternative-mt--option-3)

**Comment by iparask** [comment]
I think this is the place where it should go. I would like to add some information. Stampede 2 has the Intel Xeon Phi 7250. According to [TACC documentation](https://portal.tacc.utexas.edu/user-guides/stampede2#overview-phase1computenodes) this processor has 68 cores and 4 **Hardware** threads per core, reaching 272 hardware threads in total.

RP's SLURM resource manager checks only the ```$SLURM_NPROCS``` environment variable. That provides the number of cores and not the total number of threads that are available. If the ```$SLURM_CPUS_ON_NODE``` is checked then we get all 272

```
c455-032[knl](3)$ echo $SLURM_CPUS_ON_NODE
272
c455-032[knl](4)$ echo $SLURM_NPROCS
68
```

Assume the following two scenarios:
1. 68 OMP CU, where each CU just wants 4 threads.
2. Hybrid OMP-MPI CU that wants 68 process and 4 threads per process

Although these scenarios are very specific, they show that it will be easy to waste 75% of the computing power of this system.

This raises the question, whether or not there is a need to take into account processors that offer hardware threads for supporting multithreaded units.

**Comment by andre-merzky** [comment]
Thanks for the info, @iparask!  I would think that the use case is actually covered by the approach implemented in the gpu branches - but indeed, the slurm resource inspection should take `$SLURM_CPUS_ON_NODE` into account.  That though is worth a new ticket I think.

Thanks!

**Comment by vivek-bala** [comment]
This has been addressed by the new CUD. Closing.
