### ISSUE TITLE
update tutorial examples for v0.46

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1388]
AM to sync with @franklinbetten, William

**Comment by FranklinBetten** [comment]
Several questions

1. Want to clarify that by tutorial examples you mean the examples on the documentation [page](http://radicalpilot.readthedocs.io/en/latest/) 

2. It says tutorial examples for v0.46 however the documentation page is only for 0.45.3. So should I wait until someone has finished testing on a machine before I check the tutorial examples or would it be best for me to just do the tutorial examples with 0.45.3 tutorials since 0.45.3 and 0.46 might not be too different? 

3. Also a little bit of clarification on what you want me to do when I find an issue on the wiki or in one of the RP tutorial scripts. Do you want me to make the changes or to make a ticket for each problem I find?

**Comment by iparask** [comment]
As per request by Franklin

**Comment by andre-merzky** [comment]
Hi Franklin, 

sorry for the late reply :/

> 1. Want to clarify that by tutorial examples you mean the examples on the documentation page

Yes, indeed.

> 2. It says tutorial examples for v0.46 however the documentation page is only for 0.45.3. So should I wait until someone has finished testing on a machine before I check the tutorial examples or would it be best for me to just do the tutorial examples with 0.45.3 tutorials since 0.45.3 and 0.46 might not be too different?

The `devel` branch is basically the state for the planned release at this point, so feel free to work on devel, and if you have any changes, create a pull request toward devel (see below).  I'll also be updating some documentation to fix version numbers and stuff - but we expect no major changes on that level really.

> Also a little bit of clarification on what you want me to do when I find an issue on the wiki or in one of the RP tutorial scripts. Do you want me to make the changes or to make a ticket for each problem I find?

Please create a new branch (like `fix/example_00` or so), commit your changes there, and create a pull request toward devel.  Let me know if you need help with branching or pull requests!

Many thanks, Andre.

**Comment by vivek-bala** [comment]
I believe the examples have been updated since then. Closing as old.
