### ISSUE TITLE
Example #0 fails using Anaconda

### ISSUE THREAD

**Issue by ethan-campbell** [radical-cybertools/radical.pilot#1407]
`00_getting_started.py`, cloned from this repo and unmodified, terminates with the stack trace below. I'm using Anaconda in a Python 2.7 conda environment on MacOS. Output of radical-stack:

> python            : 2.7.13
> virtualenv        : None
> radical.utils     : 0.45
> saga-python       : 0.45.1
> radical.pilot     : 0.45.3

and the errors:

> 2017-08-03 19:29:44,315: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : [Callback]: ComputePilot 'pilot.0000' failed -- calling exit
> 2017-08-03 19:29:44,315: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : sys.exit from callback
> Traceback (most recent call last):
>   File "/Applications/anaconda/envs/py27/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 235, in call_callbacks
>     cb_func(self._shared_data[pilot_id]['facade_object'](), new_state)
>   File "/Applications/anaconda/envs/py27/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 251, in _default_pilot_error_cb
>     sys.exit(1)
> SystemExit: 1
> ps: illegal option -- -
> usage: ps [-AaCcEefhjlMmrSTvwXx] [-O fmt | -o fmt] [-G gid[,gid...]]
>           [-g grp[,grp...]] [-u [uid,uid...]]
>           [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]]
>        ps [-L]
> 
> RADICAL Utils -- Stacktrace [18670] [MainThread]
> 
> Traceback (most recent call last):
> File "00_getting_started.py", line 100, in <module>
> umgr.wait_units()
> File "/Applications/anaconda/envs/py27/lib/python2.7/site-packages/radical/pilot/unit_manager.py", line 710, in wait_units
> time.sleep (0.5)
> KeyboardInterrupt
> 
>
> Traceback (most recent call last):
>   File "00_getting_started.py", line 121, in <module>
>     session.close(download=True)
> TypeError: close() got an unexpected keyword argument 'download'

**Comment by iparask** [comment]
Hello,

I assume you are running this on your local Mac. RADICAL-Pilot creates a virtualenv on the fly, which can be found on the ```radical.pilot.sandbox``` folder that is created. Anaconda has its own way of creating virtual environments, by using ```conda``` instead of ```virtualenv```. For that reason there are resource labels that include the suffix ```_anaconda```.

Please delete the ```radical.pilot.sandbox``` folder and run the examples like:
```
python 00_getting_started.py local.localhost_anaconda
```
instead of 
```
python 00_getting_started.py
```

This is true for all the examples.

**Comment by andre-merzky** [comment]
@ethan-campbell, did this solve your problem?  Please let us know if you need support to get this working.

**Comment by ethan-campbell** [comment]
Thanks for the pointers. Yes, I'm running it locally. Deleting the `radical.pilot.sandbox` folder and running the example as specified resolves all but the final error message:

> Traceback (most recent call last):
>   File "00_getting_started.py", line 121, in <module>
>     session.close(download=True)
> TypeError: close() got an unexpected keyword argument 'download'

Changing line 121 (`session.close(download=True)`) to simply `session.close()` gets rid of this error. A `radical.pilot.sandbox` folder is still being created in my home folder, containing directories named `ve_localhost` and, e.g., `rp.session.Ethans-MBP-2.Ethan.017384.0005-pilot.0000` (one per run). I assume this behavior is normal?

Setting verbose logging via `os.environ['RADICAL_VERBOSE'] = 'DEBUG'`, I see multiple traces similar to the following. Does this indicate failure of the CUs?

> 2017-08-05 23:12:16,430: radical.saga.pty    : MainProcess                     : Thread-9       : DEBUG   : read : [   17] [  304] (17736.0:RUNNING: \n17736.0:FAILED:1 \n18002.0:RUNNING: \n18002.0:FAILED:1 \n18766.0:RUNNING: \n18766.0:FAILED:1 \n24258.0:RUNNING: \n24258.0:FAILED:1 \n25273.0:RUNNING: \n25273.0:FAILED:1 \n25917.0:RUNNING: \n25917.0:FAILED:1 \n26500.0:RUNNING: \n26500.0:FAILED:1 \n27086.0:RUNNING: \n27921.0:RUNNING: \n)

**Comment by andre-merzky** [comment]
Hi Ethan, 

> `session.close(download=True)` 

The download parameter was only recently introduced, to fetch profiles and logfiles from the remote site.  It seems that the example version is out of sync with the installed stack.  Thanks for the hint, I'll make sure this is corrected for our next release.

> radical.pilot.sandbox

Yes, that is expected behavior.  You'll also see those sandboxes created on any remote target resources, should you run the examples toward those.  The `ve_localhost` is kept around to speed up bootstrapping for subsequent runs.  The pilot and unit sandboxes are kept around for mostly debugging purposes, but also because several of our users wanted it that way.  We have some flags to clean the sandboxes out after a successful runs, FWIW: set 'cleanup=True' in the pilot description.  But I am actually not sure if this is enabled right now, need to check - we usually don't use that option to be honest...


> 2017-08-05 23:12:16,430: radical.saga.pty : MainProcess : Thread-9 : DEBUG : read : [ 17] [ 304] (17736.0:RUNNING: \n17736.0:FAILED:1 \n

The traces you see are not from the RP layer, but from the SAGA layer, which is our lower level resource interface.  In this case it picks up the state of all current and *former* jobs which have been running on localhost, and for which some job traces are still around.  Those jobs refer to the *pilot jobs* (and some additional utility jobs), not to the compute units.  The states you see there are thus not reflecting unit states.

FWIW, SAGA and RP share some part of the job and unit state models, thus the similar state names...

**Comment by ethan-campbell** [comment]
Thanks, Andre. These are helpful tips.

FWIW, setting `cleanup=True` in the `pd_init` dict doesn't seem to be clearing out the sandbox/session directories after execution.

Happy to close this issue unless you'd like to keep it open as notes for a future release.

**Comment by andre-merzky** [comment]
Thanks for the ping-back!  If its ok for you, the ticket can be closed: the `download` parameter is in for the next release, and I'll open a separate ticket to check the `cleanup` semantics.

Let us know if you need anything else!
