### ISSUE TITLE
Upper limit to the number of CUs that can run on one pilot on OSG?

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1428]
I submitted 1 pilot to OSG and 1024 CUs, each running `/bin/true`, on that pilot. After running 359 CUs successfully, the CUs no longer execute. I checked the log files on the client side, but found no errors that explains the error message (The error messages I think are from me tearing down the pilot and the session). I was unable to ssh to the OSG node, so no agent logs.

Is there documentation on upper bound on the number of CUs that a pilot can execute?

Here are the logs, in case you want them.
[rp.session.two.mingtha.017408.0023.zip](https://github.com/radical-cybertools/radical.pilot/files/1265294/rp.session.two.mingtha.017408.0023.zip)

**Comment by mturilli** [comment]
If you submitted a single job to OSG, that job may have been killed while you were still using it. This is a 'normal' behavior on OSG where the notion of walltime does not apply.

**Comment by mingtaiha** [comment]
I checked `condor_q` and found that the job to which my pilot was associated was still running. So it seems that my job was not cancelled, but rather that no more CUs were running. Have you seen this before Matteo?

**Comment by mturilli** [comment]
Difficult to say. Did you see errors on RP related to the communication with the agent? Was the state of the job running as different from suspended?

**Comment by mingtaiha** [comment]
To answer your questions:

There didn't seem to be any errors on RP related to communication with the agent. All the errors I saw were just from me tearing down the session.

The state of the job (according to `condor_q`) was Running, so everything seemed to be ok.

**Comment by andre-merzky** [comment]
Hi Ming - the client logs are unfortunately not very conclusive.  Do you happen to have a non-empty tarball of logfiles on the target host (the osg submission host)?  If not, can you please send the condor logfile which should sit in the the pilot sandbox dir on that machine.

One option is that the pilot got migrated, which we don't survive unfortunately (but also can't prevent from happening).  But, the pilot should actually be dead after such a migration.

FWIW, we do not have any hard limit on CUs per pilot on OSG.  But, we have seen that pilots on OSG fail often and frequently, and that is something your application will have to be able to handle in order to sensibly make use of OSG.

In general I found debugging of pilot failure modes on OSG very difficult, as we rarely get any logfiles back... :/

**Comment by mingtaiha** [comment]
I didn't get agent log files. I wasn't able to ssh to the target host. But it's good to know that the problem is with how pilots behave with OSG, and not a problem with scheduling CUs to execute

**Comment by mingtaiha** [comment]
I'll close this since the question is answered. Thanks
