### ISSUE TITLE
Does RP support data staging when submitting jobs to OSG?

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1429]
Title says it all

**Comment by andre-merzky** [comment]
No, not really - since we do not know where exactly the Pilots / CUs will end up, we can't *push* data there.  So for staging, the only sane option is that the pilot *pulls* data for the CUs.  That is not fully implemented in mainstream RP.  There exists some support for pulling data from an SRM endpoint, and that has been specifically been developed towards use on OSG - so that is something you can build upon, if you so want.  That code though has a number of hardcoded assumptions, like the service endpoint  URLs etc., so the general use case will likely not work out of the box.

**Comment by mingtaiha** [comment]
Thanks. That's good to know.
