### ISSUE TITLE
Possible to increase concurrency of remote-remote file transfer?

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1435]
I have a ~7GB file on superMIC that I need to read in each of my CUs. The CU kernel is I/O intensive (about 3-5 mins to read, execution is sub second) and reading from the same file increases the total time dramatically. So I tried to create a copy of the file inside each unit folder (thus each CU works only on 1 copy of the file). Currently, 1 copy instruction seems to be running at a time. Since the file movement time is large and execution time of each CU is small, the execution of all CUs looks like it is serial.

Can the number of concurrent file movement be increased? Thanks

**Comment by andre-merzky** [comment]
You may want to be careful with that use case: we can increase concurrency, but it will load the file system.  Well, you have a small number of large files, which usually is handled better than the inverse case, but still.

You can increase the number of staging components.  That will result in multiple units being handled concurrently.  You change that value [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/agent_default.json#L109) (for non-cray agents).  You can also create sub-agents with stagin components - look around line 40 in the same file, but use `"target": "node"` to move that sub-agent to a different compute node (otherwise it will not really help spreading the load on the shared FS).

Let me know how that goes!  I would suggest to not get your hopes up though: I am not sure if explicit copies will perform much better than the implicit read-only caches by the shared FS.  You may want to make sure though that the files are explicitly opened in read-only mode: RO caches are much quicker and cheaper than RW caches...

**Comment by vivek-bala** [comment]
> You may want to be careful with that use case: we can increase concurrency, but it will load the file system. Well, you have a small number of large files, which usually is handled better than the inverse case, but still.

I agree. Creating copies is not a good solution since that means if I have 1000 CUs I create 7000GB of redundant data. I think this can be improved by making changes to the application kernel, I'll discuss that with the developers.

> You can increase the number of staging components. That will result in multiple units being handled concurrently. You change that value here (for non-cray agents). 

Great, I'm going to try that out ! Just curious, why is the default one?

> You may want to make sure though that the files are explicitly opened in read-only mode: RO caches are much quicker and cheaper than RW caches...

Thanks! Didn't know that, I'll check that.

**Comment by andre-merzky** [comment]
> Great, I'm going to try that out ! Just curious, why is the default one?

Puh, I am not sure I can answer that confidently...  

Note that you can in principle have multiple instances for all components, in umgr, pmgr and agent, there also over different sub-agents -- but you can only have one instance of the umgr scheduler and one of the agent scheduler.

>> You may want to make sure though that the files are explicitly opened in read-only mode: RO caches are much quicker and cheaper than RW caches...
>
> Thanks! Didn't know that, I'll check that.

Think of it this way: on RW, the FS needs to order and sync the writes, so needs to lock the respective sections of the file (or the whole file if its dumb).  Also, it needs some mechanisms in place to keep all local caches in sync, in both directions, in case something gets written.  On RO that all does not matter - a cache is allowed to become stale, syncing can be relaxed, etc.

**Comment by vivek-bala** [comment]
Closing. Question->Answered!
