### ISSUE TITLE
Use Andre's credentials for Jenkins acceptance tests on remote resources

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1437]

**Comment by mturilli** [comment]
This is precondition to enable automatic testing of all the examples on all the resources  officially supported.

**Comment by andre-merzky** [comment]
Alas, for most resources I use gsissh, so it won't work for those...  Here a list of plain ssh resources (need to check myself...)


  * comet (amerzky)
  * archer (merzky3)

Uhm, I am afraid that is it already.  Bridges allows ssh, but no public key, so that does not help, really... 
 All others are either  token-based over ssh, or gsissh.  Alas, I don't have a long living credential, but only can obtain short-living proxies from NCSA's myproxy.  One option would be that I create that credential on the Jenkins machine once a week...
￼

**Comment by mturilli** [comment]
Agreed in f2f discussion to enable gsissh AA

**Comment by vivek-bala** [comment]
Closing as resolved.

**Comment by andre-merzky** [comment]
@vivek-bala : I don't think this is resolved, really.  But I also don't know who would pick this up either... :/

**Comment by andre-merzky** [comment]
outdated
