### ISSUE TITLE
Discuss closing master to direct pushes

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1439]
The idea is to avoid direct merging into master without creating a release candidate tag. Currently, we have a test that runs all the examples on localhost every time a RC tag is created. By enforcing this policy, we would mitigate the risk to break master as it happened with 0.46.

**Comment by itomaldonado** [comment]
Example:

<img width="788" alt="screen shot 2017-09-05 at 7 23 46 pm" src="https://user-images.githubusercontent.com/8411264/30087636-c4df06c4-926f-11e7-8eb1-dc1973184495.png">

**Comment by andre-merzky** [comment]
I am not arguing with the proposal, but want to re-iterate that the release break would *not* have been caught by that - the break appeared due to a setuptool update *after* the release happened.  Tests will help - but they will not be foolproof, and things like this will happen again, if the past of Python deployment changes is any indication for the future, so lets keep our expectations in check ;)

**Comment by andre-merzky** [comment]
The proposed restrictions have been applied.  Note though that unless we *do* have code reviews, that will not effectively change much (beyond creating an overhead for the release procedure).  I'll also apply this to RU/RS/RA.

**Comment by andre-merzky** [comment]
For RP I ticked 'pass Jenkins' as merge prerequisite.  On the other Repos we don't have that integrated yet, so that should be updated once Jenkins can flag them.

**Comment by itomaldonado** [comment]
Aww, I wanted to comment...

Anyway, I agree with Andre in some points but here is a few I think we aren't seeing eye-to-eye.

Here are some points and my thoughts right below them.

1. **If something breaks now, we can make sure we test for it later (in an automated way).**
  - I agree that an update in setuptool would not have been caught but part of the point of having a framework for automated test cases is that *if* we find an issue that does break our code, we find how to test for it and add it to our list of tests so if it happens again in the future we are prepared. Because I am willing to bet that if there is another setuptool update or something with pip happens after a release is done we won't know until an issue is opened against us.


2. **Tests take a bit to get used to early on, but get better with time.**
  - Also agree here, tests are *not* foolproof, they are a pain early on in the process, but get much, much, better as time goes and we get to have better/more comprehensive tests as long as we have the mindset that everything that breaks, we implement, needs to be testable in an automated way. If we get a into that habit the overhead we suffer now will payoff in the long run for everyone. 
  - One more thing about overhead, I am OK with the overhead being that we wait for an automated process to finish rather than having us (Andre mostly 😛) run a bunch of manual tests before a release, since all the other steps (PR devel->master, merging, etc.) need to happen anyway.


3. **Code reviews are great but suffer from the same issues from automated test cases, a pain early on but get better with time.**
  - One last thing, I agree with expectations, we should know that tests will do what we have them do, so we can't assume that tests will catch all. Having code reviews will also help. You can force code reviews in GitHub but it only provides an "I approve" button to the PR reviewers, it doesn't really force the person to review changes, so reviews may also not be the best thing either early on, but as tests do, it'll get better as we get more familiar with the code.

**Comment by andre-merzky** [comment]
> One more thing about overhead, I am OK with the overhead being that we wait for an automated process to finish rather than having us (Andre mostly ￼) run a bunch of manual tests before a release, since all the other steps (PR devel->master, merging, etc.) need to happen anyway.

Oh, I mean the overhead of having an additional merge PR, a review on that (which will only work using the github GUI) etc -- that will all eat up time, and are additional steps compared to now (Right now doing the release is just a couple of commands on the command line).  But no worries, I'll get used to that.

But, BTW, I am not sure how easy code reviews on the release PR are: ideally, the code was already reviewed before being merged into devel.  Those PRs to devel are supposed to be reviewed, and are also relatively easy to cover since any devel-PR is on a specific feature or fix.  A release-PR from devel to master however will cover several features and many fixes in *one* PR, which will be very hard to digest...  Also, by definition the diff between that PR and devel is zero, so I don't really see how tests could behave differently than in devel proper?

For hotfix releases that makes sense though, as those do usually not go through devel.  At the point where we do hotfix releases, things in master are already broken though :P

I am all for testing automatically instead of manually (although I am less optimistic about the doability, as you know :) )  And, FWIW, I do want more code reviews...
