### ISSUE TITLE
How many cores/nodes does the RP agent require

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1469]
I wanted to know the following:

* On which resources does RP agent need 1 core?
* On which resources does RP agent need 1 node?
* Which parameter(s) does this depend on?

It might be useful to document this and put it in the RTD as well

**Comment by andre-merzky** [comment]
This depends on the agent configuration: any sub-agent can be configured to run on a compute node, and in that case that compute node will not be available for the workload execution.  Its currently always a full node (not a core).

Now, the Cray's kind of require us to use sub-agents, so the default configuration on the cray has one sub-agent, so we use one node there.  Otherwise the default agent config has no sub-agents, so no compute node is reserved.

This is a somewhat simplified picture, apologies.  I agree that needs better documentation.  From the discussions over the last weeks, I would by now favor the mode where we internally add the required number of cores/nodes to the job size, so that the requested pilot size is always fully available to the workload.  Happy to use this ticket to discuss this, let me know if you have any thoughts...

**Comment by vivek-bala** [comment]
> add the required number of cores/nodes to the job size, so that the requested pilot size is always fully available to the workload

I don't think we do this. Do we? I think when we require a node for the agent, we expect the user to add a node for the agent. If we require a core, then we take one core from the resources the user requested. @andre-merzky Can you confirm that?

**Comment by andre-merzky** [comment]
We never reserve a core - we either reserve a node, or co-locate the agent and the tasks on the first node, or run on the MOM node (not affecting the compute nodes at all).  But no, the documentation has not been updated I think.

**Comment by vivek-bala** [comment]
When we co-locate the agent and tasks on the first node, do they use the same core? Wouldn't that mean that some tasks would be slower (even if the workload is homogeneous) due the interference from RP components?

**Comment by andre-merzky** [comment]
> When we co-locate the agent and tasks on the first node, do they use the same core? Wouldn't that mean that some tasks would be slower (even if the workload is homogeneous) due the interference from RP components?

Yes, indeed.  We rarely use that setup though, almost all newer and larger machines have MOM or Batch nodes which we use to host the agent.  If the agent's performance impact is impacting the workload (say, for a highly uniform BoT), then I would recommend to pick an agent config which reserves a node for the agent.

**Comment by mturilli** [comment]
Should we create a documentation page and basically write this down? I would probably add it to the section about RP architecture. Find a draft here: https://docs.google.com/document/d/1N_ssDEP9E_kIqRtaOaS-HaX0XGv5s6xU1okoZAdZxJc/

**Comment by andre-merzky** [comment]
Proposal: make explicit, but allow user to leave additional agent allocation to RP?

**Comment by andre-merzky** [comment]
add to #2331

**Comment by andre-merzky** [comment]
Proposal: add additional `PilotDescription` key `agent_nodes` to make the total node count explicit and transparent.

**Comment by andre-merzky** [comment]
Closing as outdated
