### ISSUE TITLE
Session silently continues when a pilot fails to create the directory in the sandbox

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1474]
The log/prof files created during the lifetime of the session can occupy a lot of disk space. On resources like Bridges, which gives user a smaller disk quota, it is easy to run out of memory. So, it is not uncommon for the pilot to be unable to create the session directory in the sandbox of the target machine. 

The troublesome part is that when a pilot fails to create the session directory, the session seems to quietly continue. An error (exception?) should be thrown when this happens that allows the user to catch this problem and act accordingly.

**Comment by vivek-bala** [comment]
Hey @andre-merzky , based on my reading of the bootstrapper I presume this scenario may still occur. Do you agree? Any ideas/proposals to fix this issue?

Also note that a similar failure may happen while the tasks of the application create data as well (or sftp data), i.e., IF the logs and profiles of RP did not exist, the tasks would have had enough space, but because of the logs/profs there is not enough space currently. We should document an estimate on the amount of disk space that logs/profs will take (as a function of tasks?) to keep the user aware.

**Comment by andre-merzky** [comment]
I am surprised that the session would continue.  I would expect the BS to fail in this case, causing the pilot job to fail, causing the session to terminate (if the `terminate_on_error` is set).  This needs to be looked into.

As for profile and log size: yes, it is a function of number of tasks, but also of task runtime. On machines where space is tight I would recommend to simply turn off logging and profiling, and only turn on when its needed.  If its needed, then well, there is not much one can do about the space requirement.  I don't think we can give a fair approximation of the space required.

**Comment by mturilli** [comment]
Outdated
