### ISSUE TITLE
Bootstrap fails with existing VE

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1497]
I am getting this error on Stampede2 when the VE exists. I am using the experiment/cybermanufacturing branch and the rc stack.
```
2.8589,ve_activate_start,bootstrap_1,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,
Error: did not expect more than one argument.
    (Got /work/03170/tg824689/stampede2/radical.pilot.sandbox/ve.xsede.stampede2_ssh.0.47 default)
Loading of virtual env failed!
```

Any ideas? Deleting the VE is not the fix, because as soon as I am going to reuse that VE I will get the same error.

**Comment by andre-merzky** [comment]
Can you please attach both, `bootstrap_1.out` and `bootstrap_1.err`?

**Comment by iparask** [comment]
The ```bootstrap_1.out``` is [here](https://gist.github.com/iparask/ed383a771104abfb522689b01257f237). ```bootstrap_1.err``` is empty

**Comment by iparask** [comment]
Is there a space when this argument is passed to the bootstrapper? Also can you point me to the line you saw that?

**Comment by andre-merzky** [comment]
In your output, line 239 has the correct VE name.  The profile entry in line 240 looks correct, too.  In the [bootstrapper](https://github.com/radical-cybertools/radical.pilot/blob/rc/v0.46.3/src/radical/pilot/agent/bootstrap_1.sh), this is generated in line 786.  The next active line is 798, which tries to activate the VE - thus my guess -- the next visible call would otherwise be on line 826, which I would expect to give a different output on failure.  

But I am not sure if you use anaconda in the first place, nor do I see why the args would get folded into one.  Can you check you config file?  Also, maybe sprinkle some `echo`s around that code section to get some idea on whats up with the args?

**Comment by iparask** [comment]
It is not anaconda. If you check, the first line of the output there is a ```-b``` flag set to ```default```, which means GCC python. From the VE:
```
login2.stampede2(9)$ pwd
/work/03170/tg824689/stampede2/radical.pilot.sandbox/ve.xsede.stampede2_ssh.0.47/bin
login2.stampede2(9)$ ./python
Python 2.7.13 (default, Aug  1 2017, 16:43:54)
[GCC Intel(R) C++ gcc 5.4 mode] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

I will add the some echos and see what happens

**Comment by andre-merzky** [comment]
Ah, of course - I should have seen that.  Let me know what you find... Thanks!

**Comment by vivek-bala** [comment]
Hey @iparask , any updates here? Did you manage to identify the source of the error?

**Comment by iparask** [comment]
I'm closing this ticket. The bootstrapper works on Stampede2.
