### ISSUE TITLE
ZMQError running from Titan

### ISSUE THREAD

**Issue by jrossyra** [radical-cybertools/radical.pilot#1509]
I'm running on a titan ext with the ornl.titan_aprun configuration. I have the log I found with the error message posted separately, then my working directory and sandbox tarred. 

I am running this in a python virtualenv installed under the titan python module (python version 2.7.9). In my env activate script, I have added these lines:

`export LD_PRELOAD=/lib64/librt.so.1`
`export RP_ENABLE_OLD_DEFINES=True`
`export RADICAL_PILOT_DBURL='mongodb://rp:rp@ds015335.mlab.com:15335/rp'`

[pmgr.0000.log](https://github.com/radical-cybertools/radical.pilot/files/1524973/pmgr.0000.log)
[sandbox.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1524974/sandbox.tar.gz)
[workingdirectory.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1524975/workingdirectory.tar.gz)

Let me know any other information I can provide to help, Thanks!

**Comment by andre-merzky** [comment]
Hi, 

I am afraid the ZMQ error is misleading - the original problem can be found in `pmgr.launching.0.child.log`:

```
NoSuccess: future exception: Error running job via 'qsub': 
 Job not submitted 

 size is no longer the correct way to request cores. 
  Please use the nodes option to request nodes: 
  -l nodes=<nodes>  

. Commandline was: SCRIPTFILE=`mktemp -t SAGA-Python-TORQUEJobScript.XXXXXX` &&  echo "
```

This is caused by a recent change in the batch system installation on titan.  That problem has been fixed in our code base already though - an upgrade to the devel branch (specifically for `saga-python`, but best also for `radical.utils` and `radical.pilot`) should resolve this.  This fix will be in the next release which is expected to get out in a couple of days.

Please let me know if you need help upgrading, or have any other problems with your application.

**Comment by jrossyra** [comment]
Thanks Andre, changing to the devel branch sorted it out.
