### ISSUE TITLE
DA scheduler: ssh fails on Comet with error in launch method

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1689]
Stack used:
```
$ radical-stack

  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/vivek/Research/ves/test-da-entk

  radical.analytics    : v0.45.2-103-g059830f@feature-entk-integration
  radical.entk         : 0.7.4-0.7.3-10-gaffd55e@devel
  radical.pilot        : 0.50.5-v0.50.5-96-g5c40479@project-DA-scheduler_algo
  radical.utils        : 0.50.1-v0.50.1-1-gce60836@devel
  saga                 : 0.47.6-v0.47.6-35-gf578245@devel
```

Script: https://github.com/radical-cybertools/radical.entk/blob/devel/misc/da-tagging-lfs/bin/lfs_tagging_dd.py
Error:
```
2018-08-03 15:08:06,308: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : DEBUG   : Created launch_script: /home/vivek91/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017746.0056/pilot.0000/unit.000000/unit.000000.sh
2018-08-03 15:08:06,309: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : ERROR   : Error in spawner (list indices must be integers, not str)
Traceback (most recent call last):
  File "/home/vivek91/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017746.0056/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 310, in spawn
    launch_command, hop_cmd = launcher.construct_command(cu, launch_script_name)
  File "/home/vivek91/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017746.0056/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/ssh.py", line 77, in construct_command
    host = slots['nodes']['name'][0]
TypeError: list indices must be integers, not str
```

All logs attached.

**Comment by vivek-bala** [comment]
Oops.
[rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017746.0056.zip](https://github.com/radical-cybertools/radical.pilot/files/2258939/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017746.0056.zip)

**Comment by iparask** [comment]
Can you please try again? I just pushed a fix. I think the reason was that the launch methods have not been correctly updated for the new data structure, where we have a list of dictionaries. It expected a dictionary, where each value was a list.

**Comment by vivek-bala** [comment]
Thanks Giannis. Tested it again now. There is no value for SLURM_JOB_ID even when using the ssh launch method. My tasks fail with 
```
dd: opening `/scratch/vivek91//s1_t2.txt': Permission denied
```

The lfs path set in the config file is /scratch/$USERID/$SLURM_JOB_ID/.

**Comment by iparask** [comment]
The launch method was not parsing correctly the slots data structure. It has nothing to do with the one you just pointed out, which has to do with the environment of each CU.

**Comment by andre-merzky** [comment]
Vivek - `$RP_TMP` should be exported for all units (see here) - wouldn't that be the right thing to use instead of the (system specific) Slurm environment?  See [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/executing/popen.py#L254).

**Comment by vivek-bala** [comment]
Possibly. I don't know what the initial purpose of RP_TMP was. But we set NODE_LFS_PATH based on the value in the resource config (see [here](https://github.com/radical-cybertools/radical.pilot/blob/project/DA-scheduler_algo/src/radical/pilot/agent/scheduler/continuous.py#L470)).

I think there are two issues. One as pointed above is in the launch method. The second is what the [node_lfs_path](https://github.com/radical-cybertools/radical.pilot/blob/project/DA-scheduler_algo/src/radical/pilot/configs/resource_xsede.json#L588) should be in the resource config. Initially we assumed SLURM_JOB_ID is None when we use the orte launch method, but I tried after Giannis' fix and it is still None. So the question now is what should the node_lfs_path be in the resource config file?

Giannis, do you agree with my assessment?

**Comment by iparask** [comment]
First of all, I do not understand the reason behind the line  you referenced. The environment a CU has should be as close as possible to the environment that is offered when we take a compute node from the resource's scheduler.

If you want to make it work you need to export the correct variables. @andre-merzky , why SLURM specific values are not correct, if that is what a resource documentation provides? Absolute paths without being documented will cause issues when something changes.

The ticket is because the SSH launch method did not correctly parse the data structure for the slots. `SLURM_JOB_ID` is none, because ORTE does not pass those variables correctly to the CUs executable. 

Based on `ORTE`  launch method ((here)[https://github.com/radical-cybertools/radical.pilot/blob/project/DA-scheduler_algo/src/radical/pilot/agent/lm/orte.py#L245]) any variable in the unit's description will be passed along. That being said, I am not sure how to describe it so that you can pass it.

**Comment by vivek-bala** [comment]
> First of all, I do not understand the reason behind the line you referenced. The environment a CU has should be as close as possible to the environment that is offered when we take a compute node from the resource's scheduler.

I pointed to the line where we set NODE_LFS_PATH since I believe Andre was suggesting using RP_TMP. We have an environment variable that we decided during the class specifically to map to the node lfs path as defined by the resource config.

> If you want to make it work you need to export the correct variables. @andre-merzky , why SLURM specific values are not correct, if that is what a resource documentation provides? Absolute paths without being documented will cause issues when something changes.
> The ticket is because the SSH launch method did not correctly parse the data structure for the slots. 

Agree to both.

> SLURM_JOB_ID is none, because ORTE does not pass those variables correctly to the CUs executable.

You'll note that the environment variable is None even with the ssh launch method. See my third comment. That's what I was trying to highlight.

> Based on ORTE launch method (here) any variable in the unit's description will be passed along. That being said, I am not sure how to describe it so that you can pass it.

I too had the same question. But my experiments from last week used ORTE on Comet and the environment variable got correctly parsed to the executable, i.e., did not require to be explicitly mentioned to the orte dvm.

Hope that clears up any confusions.

**Comment by andre-merzky** [comment]
Hey @vivek-bala - I am very hesitant to expose the SLURM env to the CU, as that breaks the abstraction.  Your CU would then not be portable to even localhost anymore.  `$RP_TMP` was introduced for exactly this use case: to point the CU to an RP-defined tmp storage location (which in this case happens to be the LFS) - but thus will work for any backend, not just slurm.  Does your use case need the  `SLURM_JOB_ID` env for anything else than that location?

**Comment by iparask** [comment]
So, I just realized that when we `SSH` from a node to another on Comet, the environment is getting lost. @andre-merzky , a fix like the one we have done for TACC with the `env.orig` file should solve it, at least for `SSH`.

For ORTE I am not sure what to do, as of now

**Comment by vivek-bala** [comment]
Hey @andre-merzky , I am not sure I understand how the abstraction is broken. The SLURM env variable is used **only** because that is what is specified in the resource config for comet. It needs to be specified in the resource config for every resource. Given that, can you clarify what you meant again please?

**Comment by vivek-bala** [comment]
> I too had the same question. But my experiments from last week used ORTE on Comet and the environment variable got correctly parsed to the executable, i.e., did not require to be explicitly mentioned to the orte dvm.

I am incorrect in the above statement. Since we specified NODE_LFS_PATH in the cud.environment, it does get passed to the orte-dvm and that's why I don't see an error.

Let me try to summarize here and try to bring everyone to the same page:
* NODE_LFS_PATH when set to /scratch/USER_ID/SLURM_JOB_ID fails with both SSH and ORTE (because SLURM_JOB_ID is None)
* NODE_LFS_PATH when set to /dev/shm succeeds with both SSH and ORTE (there was initial error with SSH, the origin of this ticket, which was fixed by Giannis).
* NODE_LFS_PATH will work for both SSH and ORTE since in RP we set it in the cud.environment. Any variable specified in the cud.environment is set correctly in the cu shell script (hence works with SSH launch method) and is passed to the orte-dvm (hence works with ORTE launch method).
* NODE_LFS_PATH is read from the resource config file for each resource

The issue as far as I understand now is 
* to understand whether SLURM_JOB_ID is None outside of RP ( I remember testing this using an interactive node and it came out to be None, but will confirm again)
* whether to use /scratch/USER_ID/SLURM_JOB_ID (as per Comet documentation) as the node lfs path for Comet, or not.

**Comment by iparask** [comment]
>The issue as far as I understand now is
>  * to understand whether SLURM_JOB_ID is None outside of RP ( I remember testing this using an interactive node and it came out to be None, but will confirm again)

It will be `None`. This is because doing `ssh` from a compute node to another does not move the environment variable setup from the SLURM queuing system.

> * whether to use /scratch/USER_ID/SLURM_JOB_ID (as per Comet documentation) as the node lfs path for Comet, or not.

I want to iterate once more that using absolute paths when they are not provided by the documentation of the system does not guarantee correct execution. Passing the environment does not break the abstraction in my opinion. We did the same with TACC systems so that we can load modules. I believe it is the same thing.

**Comment by andre-merzky** [comment]
> Hey @andre-merzky , I am not sure I understand how the abstraction is broken. The SLURM env variable is used only because that is what is specified in the resource config for comet. It needs to be specified in the resource config for every resource. Given that, can you clarify what you meant again please?

We specify many things in the resource configs which are not supposed to get leaked to the unit, like pre_bootstrap commands etc.  The resource config is to configure the agent, not the units.  The agent is thus configured to use some local file system (which happens to depend on `$SLURM_JOB_ID`).  Imagine that file system would depend on `$PBS_JOB_ID` - would we then expose that to, and expect the application to understand that too?  What breaks in terms of abstraction is that the application then has code like this:

```
if running_on_slurm:
   fin = open("..." % os.environ(SLURM_JOB_ID)
elif running_on_pbs:
   fin = open("..." % os.environ(PBS_JOB_ID)
else:
  raise
```

where the whole JOB_ID thing only commes into play because the *agent* is configured one way or the other.  You should not need to change application code just because the agent gets reconfigured differently tomorrow...

Thus, if the application needs information about that location (and I agree it does), then we should set an `RP_*` variable which will have the same name on all machines, for all configurations, and reports the required info.  This is why `$RP_TMP` exists.  If you prefer a more canonical way to inform the application, I am all for it (like using [`$TMPDIR`](http://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap08.html)) - but I would really like not to see agent configuration details reflected on in application code.

**Comment by iparask** [comment]
As far as I know this is resolved and closing as such.
