### ISSUE TITLE
Unit tests for mpirun

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1760]

**Comment by andre-merzky** [comment]
Hi @lee212 - I made some changes to the `mpirun` launch method.  More specifically, I re-unified the different flavors of `mpirun` we support (`dplace`, `ccmrun`, `mpt`, `rsh`).  Those were previously spread over different files, which though duplicated most of the code.  The small differences have now been converted into small conditionals.  

This should not really change the *default* `mpirun` LM, but please do let me know if you see something indicating otherwise, or if you need help navigating the code, etc.

FWIW, and for the record: most MPI implementations actually use the same syntax for `mpirun` and `mpiexec` - RP still treats them differently,  but cleaning that up needs more caution and time than I want to spend on it right now.
