### ISSUE TITLE
ompi installation on Titan 

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1770]
Using `ornl.titan_orte` the `STDERR` of all the CUs are showing an `ompi` failure. I was able to reproduce the error 2x. The executable is `NAMD` module, each CU executes on a single node. I can try a non-MPI NAMD executable. 

```
[PE_0]:_pmi_alps_sync:alps response not OKAY
[PE_0]:_pmi_init:_pmi_alps_sync failed -1
```

stack: 

```
radical.entk         : 0.7.8-0.7.8@master
radical.pilot        : 0.50.20-v0.50.20-1-g38b56487@fix-titan_deactivate
radical.utils        : 0.50.2-v0.50.2@master
saga                 : 0.50.3-v0.50.3@master
```
Tarball is too large, sent via slack

**Comment by andre-merzky** [comment]
I don't see anything wrong with this run's configuration - the same configuration seems to work ok for me.  The only difference really is the workload.  I think the problem is this:

```
$ module load namd

$ which namd2
/sw/xk6/namd/2.10b/cle5.2up04_gnu4.9.0/bin/namd2

$ ldd /sw/xk6/namd/2.10b/cle5.2up04_gnu4.9.0/bin/namd2 | grep libmpi
        libmpich_gnu_49.so.3 => /opt/cray/lib64/libmpich_gnu_49.so.3 (0x00002b38b75d1000)
```

Even though you don't run NAMD as MPI application, it seems to call into the MPICH stack, which will fail due to the ORTE startup.  Do you happen to have a proper non-MPI namd on titan?

**Comment by lee212** [comment]
@jdakka , following up this, how about non-MPI NAMD? if you tried.

**Comment by andre-merzky** [comment]
OMPI support was discontinued on Titan...
