### ISSUE TITLE
Running MPI workflows on Summit

### ISSUE THREAD

**Issue by kshitij-v-mehta** [radical-cybertools/radical.pilot#1920]
Hello,
I am posting here as the radical-pilot-users google groups does not seem to exist.

Does RADICAL Pilot work on the Summit supercomputer at ORNL? If so, how does it interface with the ‘resource set’ functionality on Summit?
Secondly, is there a way to specify parameters such as number of ranks per node when you run an MPI application on a supercomputer?
 
Thanks for your help,
Kshitij Mehta
Scientific Data Group
Computer Science and Mathematics Division
Oak Ridge National Laboratory

**Comment by andre-merzky** [comment]
Ugh, what's up with the mailing list?  It should exist.  Did your mail bounce?

Re summit: We are not fully done with testing, and specifically did not yet test beyond 30 nodes or so - but in general our Summit support is coming along ok right now.  At the moment we would max out at about 1k concurrent tasks in the default configuration - going beyond that requires configuration changes in our stack which are not enabled by default.  But we are also aware of some problems we have with Summit still.  Specifically our handling of the SMT settings is somewhat incorrect - we cannot place different tasks concurrently on hardware threads on the same core.  That is something our scheduler does not yet take into account - but a workaround is in place.

resource sets: we internally create ERF resource specifications for each task.  I am not sure if that answers your question though?  We do not support user specified resource sets.

> Secondly, is there a way to specify parameters such as number of ranks per node when you run an MPI application on a supercomputer?

Well, not really.  The basic assumption of our stack is that the user specifies the workload, and our stack decides how that workload is mapped to the available resources.  That might not yield the absolute optimal solution for specific workloads, but it does provide flexibility for many different workloads.

In that sense you cannot specify the exact layout of your application tasks.  You can specify its *requirements*: number of processes, threads per process, number of GPUs, input data, etc.  Our stack will then, depending on resource availability and other tasks in the workload, decide where and when to run that task.  Assuming you requested 10 nodes, and you have 1k tasks, each having  5 ranks where each rank needs 8 hardware threads (for OpenMP).  You would specify:

```
cud = rp.ComputeUnitDescription()
cud.executable = '/foo/bar'
cud.cpu_processes = 5
cud.cpu_process_type = rp.OpenMPI
cud.cpu_threads = 8
cud.cpu_thread_type = rp.OpenMP
```
you basically create 1k of those and pass them to the stack.  Our scheduler will then place the first fife ranks on hardware threads `0, 8, 16, 24, 32` (5 ranks), and each rank would have 8 hardware threads available for OpenMP threads (`0-7, 8-15, ...`).  The next task would be placed on cores `40, 48, ...` and so on.  Once all nodes are filled, we wait for a task to finish and reuse those cores for the next task, etc.

Did that make things clearer?  Don't hesitate to ping back if not :-)

Best,  Andre.

**Comment by shantenujha** [comment]
Hi Kshitij -- Just to clarify a remark that Andre made: "...beyond 30 nodes..." --- that is assuming each task is run on 1 core of each node, and thus O(1000) tasks. The limit is really on the number of tasks, not on the number of nodes, e.g.,  if each task is 2 nodes, then you can go up to 2000 nodes on summit. HtH

**Comment by shantenujha** [comment]
@kshitij-v-mehta   the mailing group does in principle exist, but GitHub ticket/issue tracker has indeed dominated activity. 

For completeness: https://groups.google.com/forum/#!forum/radical-pilot-users

**Comment by kshitij-v-mehta** [comment]
Thank you, Andre and Shantenu.

> we internally create ERF resource specifications for each task. I am not sure if that answers your question though?

Yes, thank you.

> In that sense you cannot specify the exact layout of your application tasks. You can specify its requirements

Ok. I was looking for a way to specify an exact layout (pinning) of application ranks. This includes pinning ranks from different executables on the same node using a certain layout. We have coupled applications that exchange data in memory, and want to explore placing ranks from those applications on the same node to minimize data transfer across the network. Basically, we are looking for ways to run pilot jobs where custom layouts can be specified.

> you basically create 1k of those and pass them to our software (via API calls). Our scheduler will then place the first five ranks on hardware threads 0, 8, 16, 24, 32 (5 ranks), and each rank would have 8 hardware threads available for OpenMP threads (0-7, 8-15, ...). The next task would be placed on hardware threads 40, 48, ... and so on

So, in RADICAL Pilot, the atomic unit of execution is a core. Am I understanding this right?

Thanks for your help.
P.S. I found your documentation on readthedocs to be very well written and helpful. The clear and concise documentation is appreciated.

Thanks,
Kshitij

**Comment by andre-merzky** [comment]
> We have coupled applications that exchange data in memory, and want to explore placing ranks from those applications on the same node to minimize data transfer across the network.

Ah, that's an interesting use case!  Well, we don't support that, but... :-)

Our placement is performed by a scheduler component within the pilot job.  That scheduler receives one or more tasks, and maps them to the set of available resources, *after a particular scheduling algorithm*.  Now, the algorithms we have in place are fairly simple - scheduling is not our main focus of research.  Having said that, we are able to easily plug in other schedulers, which also can evaluate additional information, like co-location tags.  In fact, we have used custom tags on tasks for other, special purpose schedulers, such as schedulers where tasks follow specific ordering, or *consecutive* tasks which land on the same compute node in order to reuse locally stored data files.

In principle it would well be possible to write a scheduler which co-locates task.  In fact, it would be fairly simple.  Naively I would create a wrapper which collects co-located tasks into one schedule request, let the existing scheduler place that task on a single node (we have such a constraint in place), and then split the allocation back into two tasks for execution.  The tasks would then start independently, but would hit the same node within a couple of seconds at most.  Going beyond that is also possible, but requires changes or plugins in other components of our stack.

Now, I do not know the context of your questions - so I have no idea whatsoever if this sounds like a worthwhile effort, or if you have other options to get your workload executed on Summit.  @shantenujha may want to give an opinion if this is a route our team could target to implement.

> Basically, we are looking for ways to run pilot jobs where custom layouts can be specified.

I understand why this seems appealing in your case.  I doubt that we would be able to support this easily.  Technically it might be feasible - but it would go against major conceptual constraints of our stack.  We focus very much on keeping the workload requirements independent from the actual resource and execution layer.  An explicit mapping would badly break this separation.  On of the major points for our stack is: once you define your workload, you can run the same script on *any* machine, and the software takes care of matching the requirements.  Specifying machine specific layouts for each task negates that principle, really.

At the end of the day though: one does what needs doing to get science done, so I am curious where this goes ;-)

> So, in RADICAL Pilot, the atomic unit of execution is a core. Am I understanding this right?

Well, its a hardware thread on summit (our default configuration runs at SMT4).  But yeah, we consider that as a core at the moment, and that's indeed the smallest atomic unit.  The set of units we reason in is:

  - thread (POSIX or OpenMP): a thread needs a 'core' and possibly a GPU
  - process:collection of threads, threads need to live within the same node 
  - task: collection of processes, which can span nodes (MPI) or need to live on the same node (POSIX multiprocessing)
  - workload: set of independent tasks
  - application / workflow: set of dependent or independent workloads 

> P.S. I found your documentation on readthedocs to be very well written and helpful. The clear and concise documentation is appreciated.

That is very kind of you to say!  We are struggling with keeping documentation up to date tbh - I am glad to hear that we seem to succeed somewhat, and that you found it useful! :-)

Best, Andre.

**Comment by shantenujha** [comment]
@kshitij-v-mehta  @andre-merzky 

Sorry for the delay in responding. I'm briefly familiar with your use case (presumedly CODAR and other multi-physics applications, I presume?) and I do think there is value in being 
able to pin "tasks" to cores, inter alia to provide custom layouts. The need and importance for this can  can only grow as tasks and nodes get heterogeneous. 

Yes, this is something we should explore but what that means @kshitij-v-mehta unfortunately, that it would be "happening overnight".  But let's discuss in a separate thread if there might be accelerated mechanisms to make this happen (via DOE space etc.). It would also feed into the agreement with Matt Wolf etc to try to work closer together.

**Comment by kshitij-v-mehta** [comment]
Thanks Shantenu and Andre. 

> I do not know the context of your questions

I am part of the ECP CODAR project, where we are looking at ways to analyze data online in scenarios where simulations generate large amounts of data. As part of it, we want to explore various workflow orchestration mechanisms. As a simple example, if you consider a simulation and an analysis application running concurrently that exchange data, we want to look at the performance when they are placed on separate nodes, when they share compute nodes, and the distribution of compute resources between them. A full study of different process placement mechanisms generates an ensemble of experiments, and we are looking at ways to manage them. Makes sense? Feel free to ping me if you have questions.

Shantenu - yes you are correct, I work with Matthew Wolf @mw70, and he mentioned that you have had discussions about this in a different context.

**Comment by iparask** [comment]
Closing as it seems to have been resolved.
