### ISSUE TITLE
Numpy dependency unsatisfied in the bootstrapper

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#2057]
This error seems nonfatal but we may want to consider to add numpy as a dependency. Numpy itself is not too heavy and it is cached most of the times anyway.
```
Collecting six
  Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
ERROR: h5py 2.9.0 requires numpy>=1.7, which is not installed.
Installing collected packages: six, munch
Successfully installed munch-2.5.0 six-1.14.0
```

**Comment by andre-merzky** [comment]
This is a secondary dependency (we don't use numpy), and its optional, too. But, more importantly, `munch` (which pulls `six`, which optionally pulls `h5p`, which pulls numpy) will go away soon due to some RU consolidation (we repeat code in the `Descriptions` and `Config` classes).  Happy to leave this issue open 'til then.

**Comment by andre-merzky** [comment]
resolved.
