### ISSUE TITLE
GPU sharing via MPS

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2140]
- MultiProcessService [presentation](
http://on-demand.gputechconf.com/gtc/2015/presentation/S5584-Priyanka-Sah.pdf)
  - DONE AM: [CU description proposal](https://github.com/radical-cybertools/radical.pilot/wiki/RFC.7)
  - TODO AA: share MPS example
  - API
  - Scheduler
  - Executor

**Comment by andre-merzky** [comment]
see #1796

**Comment by andre-merzky** [comment]
IP: https://stackoverflow.com/questions/31643570/running-more-than-one-cuda-applications-on-one-gpu

**Comment by mturilli** [comment]
Asked to a user for reference code https://github.com/radical-collaboration/hpc-workflows/issues/100

**Comment by AymenFJA** [comment]
[launch_mps.sh](https://gist.github.com/AymenFJA/2dc52f02a503d53401b2e74f7439b252)
[run_mps.sh](https://gist.github.com/AymenFJA/21e1300fe3def9c478d923eee8a15774)
[stop_mps](https://gist.github.com/AymenFJA/54598abbb3da316bf5b1614faae6ac8b)

**Comment by AymenFJA** [comment]
@andre-merzky : I am not aware of any constraints, but once you started the `MPS` all you need to be aware of is the limitations of your GPU (total GPU memory size) and that's because your total GPU memory size will be in effect on both Cuda applications(tasks) at the same time. For example, if each task allocates `3GB` of memory on the GPU, and you have a `4GB` GPU, then most likely the CUDA API functions (`cudaMalloc`) of one task will return errors.

**Comment by andre-merzky** [comment]
@mturilli , @andre-merzky : oing Wenjie for use case / test

**Comment by andre-merzky** [comment]
TODO for release: test and document

**Comment by andre-merzky** [comment]
@AymenFJA, quick question: can you confirm that you have been running MPS tasks via RP?

**Comment by AymenFJA** [comment]
@andre-merzky yes, I hard-coded everything in a `shell` script and submitted the script as a `CU` (task) using RP.

**Comment by mturilli** [comment]
For an example from Wenji, see last message at: https://github.com/radical-collaboration/hpc-workflows/issues/100
