### ISSUE TITLE
transfers should become cancelable

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#222]
Currently we have no loop of control during transfer, so we have to wait for a transfer to complete.

**Comment by andre-merzky** [comment]
Transfers are now enacted in a separate process which is killed on termination - which implicitly cancels transfers on shutdown.  Since we don't have states defined on a transfer, it makes semantically not much sense to be able to cancel them individually.  The only remaining case is unit cancellation - which should cancel transfers.  At this point, it cancels *pending* transfers.  Closing this for now, until it becomes an explicit problem in some real use case...
