### ISSUE TITLE
session files missing for experiment running on Comet

### ISSUE THREAD

**Issue by aydinsaribudak** [radical-cybertools/radical.pilot#2259]
Hi,
I start a run for deepDriveMD code on Comet. I create a conda environment to make this run. Even though I set the walltime sufficiently large (120 mins) to complete a set of concurrent simulations, I got a "time limit" error in bootstrap file as follows:
`slurmstepd: *** JOB 37030348 ON comet-31-17 CANCELLED AT 2020-11-17T01:54:13 DUE TO TIME LIMIT ***
`
Radical-stack information is as follows. 
```
(workflow-4) [aydins@comet-ln2 eh22]$ python -V
Python 3.6.12 :: Anaconda, Inc.
(workflow-4) [aydins@comet-ln2 eh22]$ radical-stack
  python               : 3.6.12
  pythonpath           : /opt/sdsc/lib
  virtualenv           : workflow-4

  radical.analytics    : ?
  radical.entk         : 1.5.1
  radical.gtod         : 1.5.0
  radical.pilot        : 1.5.5-v1.5.5-139-gd1598f08c@devel
  radical.saga         : 1.5.6-v1.5.6@devel
  radical.utils        : 1.5.4
```
the script is here:
[https://github.com/radical-cybertools/radical.midas/blob/comet/deepDriveMD_aydin_stage1.py ](url)

The session folder is attached.
[session_folder.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/5556600/session_folder.tar.gz)

Thank you,
Aydin

**Comment by andre-merzky** [comment]
Hi Aydin -- I see nothing wrong with the bootstrapper, only that it does not get very far in the allotted time.  You could try to simply run again to check if any temporary file system issues caused this.  15 min runtime should be sufficient for that, you may want to run a smaller example as to not waste too many node hours waiting for this test.

The bootstrapper creates a new virtualenv for the pilot agent to run in -- that VE is different from the conda env you use on your client side.  If another test run fails similarly, I would suggest the following (from within your client env:

```sh
export VE=/oasis/scratch/comet/aydins/temp_project/radical.pilot.sandbox/ve.xsede.comet_ssh.1.5.5
rm -rf $VE $VE.lock
module load python
radical-pilot-create-static-ve $VE
```

and then run the test again.  That should run the same code as the bootstrapper does, but from your client side, and will prepare the environment so that the bootstrapper does not have to do so.  

Let us know how that goes!

**Comment by aydinsaribudak** [comment]
Hi @andre-merzky , 
I followed the instructions to do bootstrapping from clients. 
Then I do `module unload python` before running my script because the python2 was loaded. 
I did my test with a sample script: get_started.py. Unfortunately it didnt resolve the issue.
Do you think `module unload python` command was the reason for the failure?
Thank you
Aydin

**Comment by andre-merzky** [comment]
@mtitov : would you mind having a look?

**Comment by mtitov** [comment]
@andre-merzky could it be because of not proper SLURM script? Looks like it is similar to Bridges of how GPUs are set: `#SBATCH --gres=gpu[:type]:n` ([link](https://www.sdsc.edu/support/user_guides/comet.html#gpu)). 

Also user guide states

> Users should always set --ntasks-per-node equal to 6 x [number of GPUs] requested on all k80  "gpu-shared" jobs, and 7 x [number of GPUs] requested on all p100 "gpu-shared" jobs, to ensure proper resource distribution by the scheduler. Additionally, when requesting the P100 nodes it is recommended to ask for 25GB per GPU (unless more is needed for the code).

Should this be enforced? (but looks like it only applies for `gpu-shared` queue, and not for `gpu` queue, which is used by Aydin)

@aydinsaribudak can you please try the following [SAGA branch](https://github.com/radical-cybertools/radical.saga/tree/fix/comet_gpu)

**Comment by aydinsaribudak** [comment]
@mtitov I switch Saga branch to  fix/comet_gpu as suggested.
A simple script already took almost an hour but not any progress yet. It looks like it didnt help to fix the issue.

Thank you,
Aydin

**Comment by aydinsaribudak** [comment]
@andre-merzky @mtitov @lee212 
I had a successful run recently. It worked for both get_started.py and deepDriveMD.py scripts (there is an issue with deepDriveMD but it is irrelevant).
I didnt have any changes before having a successful run. I remember I gave a try using `fix/comet_gpu` branch but I think the issue is resolved after Comet sources became less busy. I guess they were overloaded during last week.
Thank you for looking into the issue.
Aydin
