### ISSUE TITLE
Session in `00_getting_started.py` takes 100+s to complete and generates 200+ files 

### ISSUE THREAD

**Issue by nirandaperera** [radical-cybertools/radical.pilot#2581]
Hi all, 

I'm new to RP and I tried running the `00_getting_started.py` example in my cluster (using `local.localhost` config). 
It completes properly, but surprisingly it takes 100+ s to complete. And when I check the session dir, it has 200+ files. 

I am wondering if I have made any mistake here. 
Is there a way to change the session directory path? (currently all these files are being written to a dir in NFS. I'd like to redirect them to a local dir)

**Comment by shantenujha** [comment]
@nirandaperera Do you have a link / details to the cluster in issue, please?

**Comment by AymenFJA** [comment]
@nirandaperera, you should see 2 sessions (`rp.session.xxxx` or something like that) folders one where you ran from (under the working directory) and one under `/usr/home/radical.pilot.sandbox` could you create a tarball of both session folders and upload them here please so I/we can assist you in a better way.

**Comment by andre-merzky** [comment]
Hi @nirandaperera , 

sorry for the late response.

You observation is correct, and to some extent expected - but please allow me to put that in context.

Here is a graphical representation (created with the session you provided) of the pilot agent activity:

![rp session v-001 dnperera 019100 0009 util2](https://user-images.githubusercontent.com/1319674/164735462-20301e0e-1b83-4489-87d5-44eff5b986ef.png)

You will see that the agent spends most of the time in bootstrapping and only a miniscule part in task execution.  RP is tailored toward very large workloads with many thousands of tasks executed across hundreds or thousands of nodes.  To achieve that we bootstrap a fair number of components on the target resource which collectively and concurrently handle data staging, scheduling, task execution, communication with the client session, etc.  The large number of files you find in the pilot sandbox reflect those components (you will see an additional set of files for communication bridges and other facilities of the agent).

*once those components are up*, the agent performs fairly well - but that bootstrap time is a somewhat fixed overhead.

Now, *somewhat fixed* is important here: we can configure the bootstrapper to use a prepared static environment setup and to skip most of the configuration work it performs by default.  The bootstrap time will reduce in that case to a couple of seconds.  We recommend those configurations for large scale production runs.  However, they do require manual configuration and we do not document that process very well unfortunately.  It also reduces the verbosity of the startup, skips some tests etc. so that debugging becomes a bit more challenging in case of errors.  We thus usually recommend to leave the defaults in place for test runs.

Now that accounts for about 50% of the overhead seen.  The other 50% are similarly spent in configuring and starting a set of components on the  *client* side.  RP is able to handle large numbers of pilots on different resources concurrently - but that comes again with a certain complexity cost which is wasted in your case (single pilot, small workload).  Unlike the agent side, the client side overhead can, at the moment, not be configured away.  We do have plans to better  isolate the agent from the client which should allow us to use it without our current heavyweight client - but that work is just starting up.

Best, Andre.

**Comment by AymenFJA** [comment]
Closing this as no further action required.
