### ISSUE TITLE
Tutorial feedback: how do we know what are the options for resource/task properties?

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#2625]
This came up with `'resource': 'local.localhost'` and how could they know what values other than `local.localhost` to use. In my mind, we could generalize the solution creating a CL tool like `radical-ctrl`.

Attendants wanted also to know whether the format `name-resource_launch-method` was always respected as they saw it used for `localhost_flux`.

**Comment by andre-merzky** [comment]
Does `radical-pilot-resources` address this issue?  It will list all valid resource labels for the respective RP installation.

`site.resource.launch_method` is an unwritten convention (and not a good one IMHO).

**Comment by andre-merzky** [comment]
Maybe support man pages?

**Comment by eirrgang** [comment]
What is the new documentation that has been added?

In addition to listing the known resources, I think this issue was asking for details of properties/fields. That aspect of the issue may be a duplication of #2086. (Note also that #2588 is a partial duplication, but is really a specific subset of requested doc updates.)

**Comment by andre-merzky** [comment]
Ack on the documentation - the utils docs are apparently not showing up.  I opened a new issue for that (#2706)
