### ISSUE TITLE
Dedicated attribute for environment set in task launching script

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#2653]
A TaskDescription attribute `environment` is used in task exec-script, which is executed per rank (includes such attributes as `named_env`, `environment`, `pre_exec`, `pre_rank`, `post_rank`, `post_exec`), should we have a similar attribute to be used in task launching-script (currently includes `pre_launch`, `post_launch`, but mostly configurable by LM config)?

Probably we need to rethink changing name "environment" into something else? ("task environment" could sound confusing in terms of env-isolation) -> `exec_environment` & `launch_environment`?

**update** the point of such new attribute is to be used in LM to generate command(s) accordingly (when certain parameters depends on specific environment variables provided by user)

**Comment by andre-merzky** [comment]
I don't actually see the need to expose launch method environment to the end user.  

The main difference betwee `pre_launch` and `pre_exec` is the place of execution: `pre_launch` (once per task) will be executed on the batch node, `pre_exec` on the (target) compute node (once per rank).  We have use cases for both (mostly related to accessibility of different shared file systems on both types of nodes.

The place where we set the environment OTOH should not matter, as long as the application kernel gets the right environment.  But setting it in the launch script implies the danger that the launcher can break due to that environment.  Yes, a `module load other_mpi` in `pre_launch` can also break the launcher - but again, we have use cases for `pre_launch` and we [document](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/task_description.py#L434=) that `pre_exec / pre_rank` are the recommended way for task setup.  In other words: do we have a compelling use case for this request which justifies the cost of increased complexity?

**Comment by andre-merzky** [comment]
Sorry, saw your **update** only now.  Can you give an example?

**Comment by mtitov** [comment]
@andre-merzky the only example is with LM IBRun
https://github.com/radical-cybertools/radical.pilot/blob/54bb49c2a62639776eea4e2e5a4ac638e9e46bd3/src/radical/pilot/agent/launch_method/ibrun.py#L80-L83
this environment variable `TACC_TASKS_PER_NODE` should be in launch-script and it is used to generate launch command

(*) and not sure, please correct me if I'm wrong, should environment variable `MPI_SHEPHERD` (LM MPIRun) be in launch-script as well?
https://github.com/radical-cybertools/radical.pilot/blob/c065f01f9ed045efb33e0abce046f6302453ab04/src/radical/pilot/agent/launch_method/mpirun.py#L153-L158

**Comment by mtitov** [comment]
Summary on this:
- `TaskDescription` is about task setup and shouldn't modify LM options and its behavior in general (even though `pre_launch` attribute could be used for this, e.g., to set certain env variables, we recommend not to do that);
- LM should be configurable through a corresponding section in config file (it is in development to expose certain LM options per particular LM kind);

Thus, we keep `environment` attribute, and not having env-attribute for the launching-script. And a corresponding PR will update use cases mentioned above (for IBRun and MPIRun LMs) accordingly.

p.s. `pre/post_rank` attributes will be eliminated in favor of `pre/post_exec` attributes
