### ISSUE TITLE
relax env isolation to fix RAPTOR

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2988]
specifically, `LD_LIBRARY_PATH` needs to be merged, not overwritten.
see #2980

**Comment by mturilli** [comment]
This is meant to be a general purpose solution for the special case addressed on Summit.

**Comment by mtitov** [comment]
For consistency I would call the env set by LM as `env_lm_task` (not `env_lm2`), since it is env which is set by LM for the provided executable, and which at the same level as our provided env `env_task`

Speaking about the difference between env variables set by LM and by RP, I would propose that we would extend certain env variables - for example, `env_task` would contain `export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:<paths_provided_by_RP>`. 

```python
ru.env_prep(..., preserved_env=['LD_LIBRARY_PATH'])
```

Probably we can pick certain env variables, or even just `LD_LIBRARY_PATH` for now

**Comment by rcarson3** [comment]
@mtitov I think I'm running into an issue related to this for one of my studies on Summit for the ExaAM project (related to a UQ study I'm having a grad student do). I was using the develop version of the radical cybertools to try and run things, and I kept running into issues of a missing `libgfortran.so`. I'm guessing it might be due to the fact I load up an older module in  for GCC required for my executable as part of the `pre-exec` portion of the task, but radical later on modules and appends things to the `LD_LIBRARY_PATH` which I'm guessing is what's causing the issues.

I've reverted to `v1.34.0` of `saga, pilot, and entk` which seems to have fixed the issues I was running into.

I will say I haven't seen if this might be an issue on Frontier just as I have my student running on Summit for their studies.

**Comment by mtitov** [comment]
@rcarson3 hi Robert, yeah, that fix is a temporary one (and it is for GCC 9.1.0, since that what we set by default)

https://github.com/radical-cybertools/radical.pilot/pull/2992/files#diff-56e7a2035c2b5030b5b9137091ce6dca815aecc5fa143e61ba0ab506b24cbfcd

thus to avoid `LD_LIBRARY_PATH` prepend, you can do the following (since it is part of the platform/resource config and you can overwrite it - not setting anything or bring in your setup)
```
mkdir -p ~/.radical/pilot/configs
cat > ~/.radical/pilot/configs/resource_ornl.json <<EOF
{
    "summit": {
        "task_pre_exec" : []
    },
    "summit_jsrun": {
        "task_pre_exec" : []
    }
}
EOF
```
(*) Platform ID `summit` uses `MPIRUN` as a launch method, and `summit_jsrun` uses `JSRUN`

Overall that is a manual fix, that's why it depends on GCC version, general approach (which this ticket targets), will not be version dependent. With Frontier we didn't encounter necessity to change `LD_LIBRARY_PATH`

**Comment by rcarson3** [comment]
Thanks and I'll take at your suggestion when I get the chance to try it out.

**Comment by mturilli** [comment]
Closing because of lack of use case. Workaround for Summit works.
