### ISSUE TITLE
folder creation in staging area ?

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#489]
Can I keep the shared data or the output of a CU in a particular folder in the staging area ? I tried the following but that doesn't seem to create the folder "temp" but puts the file directly in staging_area/ .

```
shared_input_file_url = 'file://%s/%s' % (os.getcwd(), SHARED_INPUT_FILE)
staged_file = "%s/temp/%s" % (MY_STAGING_AREA, SHARED_INPUT_FILE)

sd_pilot = {'source': shared_input_file_url,
                    'target': staged_file,
                    'action': radical.pilot.TRANSFER
        }
```

**Comment by marksantcroos** [comment]
This might not be implemented yet, stumbled over something similar. Will investigate.

**Comment by marksantcroos** [comment]
Btw, what version are you using for all this in general? Master or devel?

**Comment by vivek-bala** [comment]
It's the RP on pypi, I believe it should be master ?

**Comment by marksantcroos** [comment]
ACK. I'll make sure this reaches the master branch then also.

**Comment by marksantcroos** [comment]
There are a couple of issues here:

First, your code ends up with this URL: `staging:////temp/shared_input_file.txt`, note the quadruple slashes, that might not have been what you intended.
(And has the effect of `staging://temp/shared_input_file.txt` with our URL implementation. Not sure if that translation is correct though, but that is how it now is.)

In general I suggest using a combination of the `Url` class and `os.path.join` instead of `'%s/%s'`.

Once this is accounted for, there was a real problem in the code though. Subdirectories would not have been created.

I have committed a hotfix to master as the code in devel has diverged.

If you can confirm it works, we will roll a release from master.

**Comment by vivek-bala** [comment]
Confirm this is working. But rp.Url() object seems to be not excepted. 
```
Exception: ('Source staging:///temp/shared_input_file.txt is neither a list or a string!', <radical.pilot.url.Url object at 0x7f1df15dd390>)
```

So I had to ```staged_file=(str)url_object```.

**Comment by marksantcroos** [comment]
Thanks for the ack.

Yeah, good point about the Url().
Let me think whether there was a reason to not do that before, otherwise I'll add it

**Comment by marksantcroos** [comment]
Fixed in devel. I'll look at merging to master tomorrow.

**Comment by marksantcroos** [comment]
Merged to master.

**Comment by andre-merzky** [comment]
Mark, can this ticket be closed?
