### ISSUE TITLE
Mpi test runs successfully but a error is printed in the logs

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#507]
RP: devel
SP: devel
RU: devel

testing/mpi_trestles.mpi runs successfully but the following error (probably spurious) is reported in the logs:
```
2015:03:18 18:29:18 37780  MainThread   saga.PBSJobService    : [ERROR   ] Error canceling job via 'qdel': qdel: Request invalid for state of job MSG=invalid state for job - COMPLETE 2545512.trestles-fe1.local
```

**Comment by marksantcroos** [comment]
I think this happens in the window that a pilot can be complete/failed and we send an active cancel.
While this window can be made smaller, it can't be closed completely I think.

**Comment by andre-merzky** [comment]
Yes, that is correct.  That you see this message is actually a  good thing (tm): it means that (a) the `qdel` command for pilot job cancellation got issued, and (b) that the in-band pilot cancellation request got enacted by the pilot.  It is only, as Mark says, that we can't influence the ordering because of a potential race condition, so the error message will appear occasionally (or even frequently).

It is a SAGA level error though which is intercepted on RP level, and will not travel up to the API layer.
