### ISSUE TITLE
bootstrapper clean slate in case of failure?

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#555]
``` pseudo
if virtenv_mode == create:

    if ve exists:
        virtenv_mode = use

    [ ... ]

    if launch failed:
       virtenv_mode = recreate
```

**Comment by andre-merzky** [comment]
In principle this makes sense, absolutely.  We should avoid too much cleverness though, to make the behavior predictable.  A default of 'update' would have almost the same behavior as above, but is less obscure, in the sense that the different modes are better defined.  Like, at the moment we define 'create' as 'use if exists, otherwise create' -- the above snippet would require a more involved definition: 'use if exists, create otherwise.  if startup fails, delete and recreate.  if startup fails again, exit'.  GIven that we have control over the configs, I'd rather keep a number of basic modes...

**Comment by andre-merzky** [comment]
The need for this reduced with the switch to version specific VEs.
