### ISSUE TITLE
Can allocate more cores then available

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/radical.pilot#573]
Launching a pilot with `cores=16` on my laptop which has only 8 cores should raise an error. Instead the pilot just starts running on 8 cores.

**Comment by andre-merzky** [comment]
As commented in your previous ticket on localhost core allocation (#557), this only happens when PROFILING is enabled, and is expected behavior, as it allows us to profile certain elements of the agent w/o wasting large amounts of resources.  For example, I can thus run the agent scheduler over 10k cores, w/o needing to actually burning 10k cores on XSEDE or anywhere...

I added text to the documentation in that respect.

**Comment by marksantcroos** [comment]
Although I dont want to spend much more time on discussing execution on laptops, this is not what the Fork LRMS currently implements.

**Comment by andre-merzky** [comment]
details *sigh*

**Comment by oleweidner** [comment]
Hm, but I don't have profiling enabled. Unless https://github.com/radical-cybertools/radical.pilot/commit/36ec1f98d31f15d8bbf497e1c8cab84b6c77e4c0 hasn't made it into the release yet, I don't think that this is fixed.
