### ISSUE TITLE
No module named netifaces Error

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#825]
RP fails to launch in Chameleon because there is no module called netifaces.

Shouldn't it be better to add any non standard python package that is used in RP as part of the dependencies during the setup phase?

**Comment by marksantcroos** [comment]
It is:
https://github.com/radical-cybertools/radical.pilot/blob/devel/setup.py#L206

**Comment by marksantcroos** [comment]
And:
https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/bootstrapper/default_bootstrapper.sh#L61

**Comment by iparask** [comment]
Okay, let me post the log tarball because for some reason it was not installed.

**Comment by iparask** [comment]
There you are:
https://gist.github.com/iparask/47efa884c78523c0d5d3

agent_0.bootstrap_2.err and agent_0.out were empty.

**Comment by iparask** [comment]
This is with the feature/yarn branch, which I merged yesterday

**Comment by marksantcroos** [comment]
Can you move `/home/iparask/radical.pilot.sandbox/ve_chameleon` out of the way (.bak) and try again?

**Comment by iparask** [comment]
I did and it run correctly.

**Comment by marksantcroos** [comment]
Ok good. So I dont know exactly what happens though.

You had an "old" ve around, which didn't include netifaces.
That is in theory not a problem, because anything not installed during creation time by the bootstrapper is installed by RP install into rp_install. (And thereby is just an optimisation)

Apparently the installation of netifaces into rp_install doesn't get picked up, which I can't really explain.

**Comment by iparask** [comment]
How about I uninstall netifaces from the ve that I have now and give it another try?

**Comment by marksantcroos** [comment]
Feel free, its easy to fix again if it breaks.
