### ISSUE TITLE
State Diagram in Documentation mismatched with Actual Timings

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#972]
I have found that the units enter the state AgentStagingInputPending before the pilot enters the state PendingActive, and the unit enters the state AgentStagingInput after the pilot enters the state Active. The actual queue time of the pilot is captured between the agent staging stages, which does not reflect the state model provided in the documentation.

Please let me know what you think. I have attached a zip containing the pilot and unit timings for the sessions for which I have found this problem.

[timings.zip](https://github.com/radical-cybertools/radical.pilot/files/153419/timings.zip)

EDIT: Grammar

**Comment by andre-merzky** [comment]
Hmm,  I am not sure how that would conflict with the state model.  Are we excluding either case somewhere in the documentation?

Assume this piece of (pseudo)code:

```
import radical.pilot as rp
session = rp.Session()
pmgr = rp.PilotManager(session)
umgr = rp.UnitManager(session)

pd = rp.ComputePilotDescription({'resource':'localhost', 'runtime':10, 'cores':10})
pilot = pmgr.submit_pilots(pd)

# pilot launching starts, will take a while since some stuff needs to be staged, 
# job needs to be submitted.  
# Meanwhile:

umgr.add_pilots(pilot)
# from here on, the umgr *can use the pilot*, no matter in what state it is.  
# The pilot cannot execute units, yet, but the umgr can schedule units to it, 
# can stage data into the sandbox, etc/

batch_1 = list()
for i in range(10):
  ud = ComputeUnitDescription({'executable':'/bin/true'})
  batch_1.append(umgr.submit_units(ud))
# so, the above batch of units get handled by the umgr, get scheduled to 
# the pilot, umgr stages input data.  But it can do no more -- the remaining 
# states need an active pilot, so those units will get into 
# AGENT_STAGING_INPUT_PENDING and wait there until the pilot picks 
# them up, which only happens once it is ACTIVE.

# lets wait for the pilot to become ACTIVE
pilot.wait(state=rp.ACTIVE)
# at this point, the units from batch_1 can continue their state progression, 
# and go into AGENT_STAGING_INPUT etc.

If we submit a second batch of units at this point, they will not stall in 
# AGENT_STAGING_INPUT_PENDING -- the pilot is already ACTIVE, 
# and can pick the up immediately:
batch_2 = list()
for i in range(10):
  ud = ComputeUnitDescription({'executable':'/bin/false'})
  batch_2.append(umgr.submit_units(ud))

# Just for completeness, lets wait for all units and then shut down:
umgr.wait_units()  # will wait for both batches
session.close()  # will cancel the pilot
```

Does that help?  Does that match what you observe?

Best, Andre.

**Comment by mingtaiha** [comment]
Thanks for the quick reply. This in fact is what I observe. 

This is the state model I am referring to: https://docs.google.com/drawings/d/1YBAYOWcUlWpl0ER_oyCpKBWRnJoy0ceeQZNrRx0m9Ds/edit

If, however, I wanted to measure the Input Staging time of each unit, wouldn't the measurement of the input staging of the first batch bet different than that of the second batch?

The first batch of units gets handled by the umgr, scheduled to the pilot, and the stages the input data, where it waits for an active pilot to pick them up. So the Input Staging time of the first batch of pilots must contain the queue time. However, the second batch of pilots will not stall since a pilot is already active. So the time it takes for the second batch to be handled by the umgr and scheduled to the pilot does not contain the queue time.

So, the time between AGENT_STAGING_INPUT_PENDING and AGENT_STAGING_INPUT represents two different things. Moreover, it is not possible to measure the time it takes for the umgr to stage the input data and for the pilot to pick up the input data for the first batch.

Also, it seems kind of ambiguous to move the unit stage to AGENT_STAGING_INPUT_PENDING before the agent exists (since the pilot does not yet exist, at least for the first batch). Could you please clarify this point so that I can better understand this process?

**Comment by andre-merzky** [comment]
> Thanks for the quick reply. This in fact is what I observe.
> 
> This is the state model I am referring to: https://docs.google.com/drawings/d/1YBAYOWcUlWpl0ER_oyCpKBWRnJoy0ceeQZNrRx0m9Ds/edit

Hmm, I see.  Well, that figure shows two state models, and shows what components are responsible for managing what state.  It should not imply that the unit state model and the pilot state model would move in sync somehow.  A pilot can be created an canceled fully independent of any unit; a unit can travel through the non-agent parts of its state model fully independent of any pilot state.

> If, however, I wanted to measure the Input Staging time of each unit, wouldn't the measurement of the input staging of the first batch bet different than that of the second batch?

No, the times in the states would be mostly the same.  What would differ is only the time spent in the `AGENT_STAGING_INPUT_PENDING` state, as the unit would have to wait for an active pilot until it can progress into the `AGENT_STAGING_INPUT` state.

> The first batch of units gets handled by the umgr, scheduled to the pilot, and the stages the input data, where it waits for an active pilot to pick them up. So the Input Staging time of the first batch of pilots must contain the queue time. However, the second batch of pilots will not stall since a pilot is already active. So the time it takes for the second batch to be handled by the umgr and scheduled to the pilot does not contain the queue time.

Staging time does not include queue time.  Staging is independent and unaware of pilot queueing.  It can be completed even if the pilot is not yet even in the queue. Only the following `AGENT_STAGING_INPUT_PENDING` state will  have to wait for the pilot to become `ACTIVE`.  So, for batch 2 the time spent in `AGENT_STAGING_INPUT_PENDING` is shorter indeed.

> So, the time between AGENT_STAGING_INPUT_PENDING and AGENT_STAGING_INPUT represents two different things. Moreover, it is not possible to measure the time it takes for the umgr to stage the input data and for the pilot to pick up the input data for the first batch.

I am not sure why that should not possible to measure?  

 - Unit goes into `UMGR_STAGING_INPUT`: umgr starts staging input
 - Unit goes into `AGENT_STAGING_INPUT_PENDING`: umgr staging input is done
 - Unit goes into `AGENT_STAGING_INPUT`: agent starts staging input
 - Unit goes into `AGENT_SCHEDULING_PENDING`: agent staging input is done


> Also, it seems kind of ambiguous to move the unit stage to AGENT_STAGING_INPUT_PENDING before the agent exists (since the pilot does not yet exist, at least for the first batch). Could you please clarify this point so that I can better understand this process?

The pilot does exist.  You are looking at the pilot state after all ;)  It is not `ACTIVE` yet, that is why the units wait to be picked up - they are `...PENDING`.  Specifically, the `AGENT_INPUT_STAGING` is the first action the pilot will do on the unit, so the unit is pending that action, ie. `AGENT_STAGING_INPUT_PENDING`.

Did that make more sense?


Let me compare to a simile: You want to send a letter to Santa Claus, and do it like this:
 
 - prepare mentally: `WRITING_PENDING`
 - write it to paper: `WRITING`
 - put it on a stack of outgoing letters: `ENVELOPE_PENDING`
 - put it into an envelope: `ENVELOPE`
 - put it into a pocket to go to the postbox: `POSTBOX_INSERT_PENDING`
 - you put it into a postbox: `POSTBOX_INSERT`
 - the letter sits in the postbox, waiting for the postman to pick up:`PICKUP_PENDING`
 - postman comes and picks it up: `PICKUP`
 - he checks the stamp and address, and puts it into he bag: `TRANSPORT_PENDING`
 - its gets shipped etc: `TRANSPORT`
 - its deposited at the north pole... etc etc, you get the point. ;)


Now, assume you write the letter at Saturday morning and you put it into the postbox.  It is in `PICKUP_PENDING`.  The postman has the weekend off, is not `ACTIVE`.  Only when he becomes `ACTIVE` on Monday morning he'll move the letter from `PICKUP_PENDING`  to `PICKUP`.

Assume you forgot to ask for a present, and write another letter on Monday noon: you put it into the postbox, and it gets picked up immediately, because the postman is active (assuming he has nothing else to do than watching that one postbox :P), so it is only very shortly in `PICKUP_PENDING`, and goes into `PICKUP` immediately, because the postman is already `ACTIVE`.

The only change for the letter, timewise, is the duration of `PICKUP_PENDING` -- it simply has to wait there until the postman passes by.  All other states can be assumed to be the same.  All states are measurable, too.

Hmm, lets see if that helps ;)

**Comment by andre-merzky** [comment]
Hey Ming - did the above clear up your  questions?

**Comment by mingtaiha** [comment]
Sorry for the late response. Your description was very helpful. It is good to know that there is no expectation for the two state models to progress in sync. Also, knowing the steps involved in the Agent Staging Input stages was very useful, and confirmed that I was not losing my marbles looking at the timings!

I still have some minor concerns about the state model. If, however, the CU requires an active pilot in order to progress to AGENT_STAGING_INPUT, then aren't the two models in sync somehow? Also, by the fact that there must be an active pilot, the input staging time contains the queue time, Is there some relationship between the pilot queue time and the first time any agent stages input on a pilot?

Thanks again.

**Comment by andre-merzky** [comment]
Your conclusion wrt. relation of pilot `ACTIVE` state and `AGENT_STAGING_INPUT` state is correct -- alle the unit states named `AGENT_SOMETHING` (*) can only be enacted by an AGENT, and thus need an active pilot!  But the only relation this implies is `t_ACTIVE <= t_AGENT_STAGING_INPUT` for all units.  

Assume you start a pilot and wait until it is `ACTIVE`, and *only then* submit a unit to the UMGR in `NEW` state.  When the unit eventually arrives in `AGENT_STAGING_INPUT`, then it will not have any relation to the pilots queue time, because that queueing happened before the unit even existed.  That is why I would be careful with the phrasing `the input staging time contains the queue time`.  The is no inclusion implied, only an ordering.

HtH, Andre.

(*)  The discussion on the call today prompts me to point out that the state `AGENT_STAGING_INPUT_*PENDING*` can be reached by a unit even when the pilot is not active.  In that state the unit basically waits (in MongoDB)   until the pilot is active and picks it up -- it is pending for the first pilot action (AGENT_INPUT_STAGING).

I would also like to point out that in many places we use 'agent' and 'pilot' interchangeably.  'Agent' really is more an implementation detail of the pilot, and refers to the pilot in `ACTIVE` state.

**Comment by andre-merzky** [comment]
Ming, let me know if we should discuss this topic further, very happy to do so.  I'll be closing this ticket though, if you don't mind, as I don't think it results in any actionables for now.
