### ISSUE TITLE
Support for greenfield.psc.xsede.org

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#994]

**Comment by andre-merzky** [comment]
Hmm, I could login to greenfield exactly two times, and now the connection times out.  Do you know if that machine is in production mode?

**Comment by mturilli** [comment]
AFAIK, it is but I could not find conclusive information. I can log into the machine.

**Comment by andre-merzky** [comment]
thx!

**Comment by andre-merzky** [comment]
A preliminary config is available in the `feature/greenfield_994` branch now.  However, that only works when requesting a single node (15 cores), since I did not manage to get `ssh localhost` to do the expected thing, ie. could not start units via ssh.  But also, the batch system declined to give me more than one node anyway, and the machine has only 24 nodes in total (IIUC -- the description is contradictory on the distinction between processors and nodes), so that might not be much issue?  

Also, the machine layout is not uniform in terms of number of CPUs and mem per node (well, per cabinett or whatever), which RP is not aware about.  

And finally: it sees my access got blocked a couple of times, possibly due to some triggered security check.  Once gsissh access is gone, it always too a couple of hours to be able to login again.  That made working with the machine somewhat painful.  It seems to be slow (compute wise) anyway.

Matteo, can you give this a try, please, and let me know if/how usable that is for you?

**Comment by andre-merzky** [comment]
We agreed that this limited support will do for now.
